-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/
local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "zhTW")
if not L then return end

L["HandyNotes"] = "|cff0080ff[地圖]|r寶藏稀有"
L["Enable HandyNotes"] = "啟用 HandyNotes"
L["Enable or disable HandyNotes"] = "啟用或者禁用 HandyNotes"
L["Overall settings"] = "全域設置"
L["Overall settings that affect every database"] = "作用於所有資料庫的全域設置"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "這些設置可以全域控制 HandyNotes 的外觀及風格。這裡的圖示的縮放和透明度會乘以外掛程式的縮放及透明度。"
L["World Map Icon Scale"] = "世界地圖圖示縮放"
L["The overall scale of the icons on the World Map"] = "世界地圖上圖示的全域縮放值"
L["World Map Icon Alpha"] = "世界地圖圖示透明度"
L["The overall alpha transparency of the icons on the World Map"] = "世界地圖上圖示的全域透明度值"
L["Minimap Icon Scale"] = "小地圖圖示縮放"
L["The overall scale of the icons on the Minimap"] = "小地圖上圖示的全域縮放值"
L["Minimap Icon Alpha"] = "小地圖圖示透明度"
L["The overall alpha transparency of the icons on the Minimap"] = "小地圖上圖示的全域透明度值"
L["Plugins"] = "外掛程式"
L["Plugin databases"] = "外掛程式資料庫"
L["Configuration for each individual plugin database."] = "為每個外掛程式資料庫單獨配置"
L["Show the following plugins on the map"] = "在地圖上顯示下列外掛程式"
L["Add Handy Note"] = "添加隨記"
L["Edit Handy Note"] = "編輯隨記"
L["Delete Handy Note"] = "刪除隨記"
L["Title"] = "標題"
L["Description/Notes:"] = "描述/注釋："
L["Show on continent map"] = "在大陸地圖上顯示"
L["Add this location to TomTom waypoints"] = "在 TomTom 中添加此位置"
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00提示：|cffeda55fCtrl+Shift+左鍵拖拽|cFF00FF00可以移動一個隨記"
L["These settings control the look and feel of the HandyNotes icons."] = "這些設置控制 HandyNotes 圖示的外觀及風格。"
L["Icon Scale"] = "圖示縮放"
L["The scale of the icons"] = "圖示的縮放大小"
L["Icon Alpha"] = "圖示透明度"
L["The alpha transparency of the icons"] = "圖示的透明程度"
L["\nAlt+Right Click To Add a HandyNote"] = true
L["ERROR_CREATE_NOTE1"] = "HandyNotes 不能創建注釋，因為它無法獲得您當前所在的位置。這通常是因為您所在的區域沒有地圖。"
L["Syntax:"] = "參數："
L["Portal"] = "傳送門"
L["(No Title)"] = "（無標題）"
L["Icon scale"] = "圖示縮放"
L["The scale of the icons."] = "圖示的縮放值"
L["Icon alpha"] = "圖示透明度"
L["The alpha transparency of the icons."] = "圖示的透明度"
L["Undiscovered"] = "未發現"
-------------------------------------------------------BFA-Achievments
-- Settings
L["Icon settings"] = "圖示設定"
L["These settings control the look and feel of the icon."] = "這些設定控制圖示的外觀及風格。"
L["World Map"] = "世界地圖"
L["Show icons on world map"] = "在世界地圖上顯示圖示"
L["Minimap"] = "小地圖"
L["Show icons on the minimap"] = "在小地圖上顯示圖示"
L["What to display"] = "要顯示什麼"
L["Show found"] = "顯示已發現"
L["Show waypoints for items you've already found?"] = "顯示你已發現的項的節點"
L["Reset hidden nodes"] = "重置隱藏的節點"
L["Show all nodes that you manually hid by right-clicking on them and choosing \"hide\"."] = '顯示所有透過您手動右鍵點擊並選擇\\\"隱藏\\\"的節點。'
L["Create waypoint"] = "創建路徑點"
L["Hide node"] = "隱藏節點"
L["Close"] = "關閉"
-- 沙丘騎手
L["Along the pyramid edge"] = "沿著金字塔邊緣"
L["On top of the slither snake"] = "在滑動的蛇上方"
L["Entrance"] = "入口"
-- 石刻
L["Inside a building ruins near the mountain"] = "在山附近的廢墟房子裡"
L["Next to broken pillar as you enter the ruins"] = "在廢墟裡面的爛柱子旁邊"
L["Island between Nazmir and Zuldazar zones"] = "納茲米爾和祖達薩之間的島嶼"
L["Near Kel'vax Deathwalker rare"] = "稀有怪死亡行者卡爾瓦科斯附近"
-- 傳說
L["Behind the NPC in the Corner"] = "在角落裡的NPC背後"
L["Above, to the right of the small staircase"] = "在上面，小樓梯的右邊"
L["Next to the river"] = "在河邊"
L["On the wall, behind the torch"] = "在火炬後面的牆上"
L["Above, at the pond on the big stone"] = "在上面，大石頭上的水池"
L["At the destroyed pillar"] = "在爛柱子上"
L["In the eye of the skeleton, outside"] = "在外面的骷髏眼睛裡"
L["Between the roots"] = "樹根的縫隙"
L["At the destroyed pillar on the left"] = "在左邊的爛柱子上"
L["Scroll on the altar"] = "卷軸在祭壇上"
L["At the destroyed wall"] = "在爛牆上"
L["Under water, at the bottom, at the destroyed pillar"] = "在水底的爛柱子上"
L["Scroll next to the altar, behind the mobs"] = "卷軸在小怪後面的祭壇上"
L["In the pond"] = "在水池裡"
L["Next to the withered tree"] = "在枯樹旁邊"
--實事求是，女士
L["Under water"] = "在水下"
L["Behind the scrub"] = "在灌木叢後面"
L["Under water at the foot of the small waterfall"] = "在小瀑布下方的水裡"
L["At the bottom of the upper waterfall"] = "在瀑布的底部"
L["Under the leaning tree"] = "在傾斜的樹下"
L["at the destroyed wall"] = "在烂墙上"
L["On the mountain, a bit difficult to find the way up (see path)"] = "在山上，有點難找（仔細看引導）"
L["Path to The Flayed Man: Start"] = "剝皮者引導：開始"
L["Path to The Flayed Man: Step 1"] = "剝皮者引導：第一步"
L["Path to The Flayed Man: Step 2"] = "剝皮者引導：第二步"
L["Path to The Flayed Man: Step 3"] = "剝皮者引導：第三步"
L["Path to The Flayed Man: Step 4"] = "剝皮者引導：第四步"
L["Path to The Flayed Man: End, jump down carefully"] = "剝皮者引導：最後，小心點跳下去"
L["In a cave, at the very back of the wall"] = "在山洞裡，在牆的背面"
L["Path to Protectors of the Forest: cave entrance"] = "森林守護者引導：山洞入口"
--Hoppin' Sad
L["Lost Spawn of Krag'wa #1"] = "迷路的卡格瓦子嗣 #1"
L["In an underwater cave"] = "在水下的洞穴里"
L["Cave entrance for #1"] = "洞穴入口 #1"
L["Lost Spawn of Krag'wa #2"] = "迷路的卡格瓦子嗣 #2"
L["Cave entrance for #2"] = "洞穴入口 #2"
L["Lost Spawn of Krag'wa #3"] = "迷路的卡格瓦子嗣 #3"
L["Between the huge roots"] = "巨大的根的縫隙中"
L["Lost Spawn of Krag'wa #4"] = "迷路的卡格瓦子嗣 #4"
L["In cave"] = "在洞穴里"
L["Cave entrance for #4"] = "洞穴入口 #4"
L["Lost Spawn of Krag'wa #5"] = "迷路的卡格瓦子嗣 #5"
L["Cave entrance for #5"] = "洞穴入口 #5"
L["Way up to the cave #5"] = "通往洞穴的路 #5"
L["Lost Spawn of Krag'wa #6"] = "迷路的卡格瓦子嗣 #6"
L["Sits up between trees"] = "在樹林中"
L["Lost Spawn of Krag'wa #7"] = "迷路的卡格瓦子嗣 #7"
L["Sits near the bridge behind the big tree"] = "在大樹后面的橋附近"
L["Lost Spawn of Krag'wa #8"] = "迷路的卡格瓦子嗣 #8"
L["Cave entrance for #8"] = "洞穴入口 #8"
L["Lost Spawn of Krag'wa #9"] = "迷路的卡格瓦子嗣 #9"
L["Sits behind a curtain of scrub"] = "在一塊磨砂的簾子后面"
L["Lost Spawn of Krag'wa #10"] = "迷路的卡格瓦子嗣 #10"
L["Sits in a ruin"] = "在廢墟中"
------------------------------------------------HandyNotes_BFA_HF_Tracker
-- Settings ---------------------------------------------------------
L["ADD to NPCScan"] = "添加到NPCScan"
L["Information for NPCScan and not available."] = "NPCScan的信息不可用"
L["Use item icons"] = "使用物品圖標"
L["Show the icons for items, if known; otherwise, the achievement icon will be used"] = "如果已知則顯示物品圖標，否則顯示成就圖標"
L["Use item tooltips"] = "使用物品提示"
L["Show the full tooltips for items"] = "顯示完整的物品使用提示"
L["Show NPCs"] = "顯示NPCs"
L["Show rare NPCs to be killed, generally for items or achievements"] = "顯示稀有怪擊殺信息，通常為道具或成就"
L["Show treasure"] = "顯示寶箱"
L["Show treasure that can be looted"] = "顯示可獲得的寶箱"
L["Junk"] = "垃圾"
L["Show items which don't count for any achievement"] = "顯示不統計任何成就的物品"
L["Debug"] = "調試"
L["Show quest ids"] = "顯示任務ID"
L["Show the internal id of the quest associated with this node. Handy if you want to report a problem with it."] = "顯示與此節點相關的任務內部ID。用于報告問題。"
L["Show NPCs ids"] = "顯示NPC ID"
L["Show the internal id of the NPC associated with this node. Handy if you want to report a problem with it."] = "顯示與此節點相關的NPC內部ID。用于報告問題。"
L["What to display achievement"] = "如何展示成就"
L["Show Achievement"] = "顯示成就"
L["Show Achievement that can be looted"] = "顯示可獲得的成就"
L["Use item icons achievement"] = "使用成就獎勵物品圖標"
L["Show Achievements completed"] = "顯示已經獲得的成就"
L["Select achievement"] = "選擇成就"
L["Show the icons Achievement"] = "宣誓成就圖標"
-- Others -----------------------------------------------------------
L["Entrance "] = "入口"
L["Start "] = "開始"
L["Require item : "] = "必要道具："
L["You can buy them from : "] = "可在此處購買："
L["in cave"] = true
-- Treasure ---------------------------------------------------------
L['Treasure Chest'] = "藏寶箱"
L['Small Treasure Chest'] = "小寶箱"
-- HF xxxxx - Trésors de Zuldazar
L["On second floor"] = "在二樓"
L["Bottom floor of ship"] = "船的底層"
L["Top of ship"] = "船的高處"
L["Event: kill Da White Shark first"] = "事件：需要先殺死大白鯊"
L["In cave behind waterfall"] = "在瀑布后面的山洞里"
L["Road behind waterfall"] = "瀑布后面的路"
-- HF xxxxx - Trésors de Nazmir
L["In dead hippo's mouth"] = "在河馬尸體的嘴里"
L["Climb the tree"] = "爬到樹上"
-- HF 12849 - Trésors de Vol’dun
L["Use mine cart"] = "使用礦車"
L["Climb the rock arch"] = "爬上石拱門"
L["Climb fallen tree"] = "爬到倒下的樹上"
L["Under sand pile"] = "在沙堆下"
L["Door on East side"] = "在東邊的門上"
L["Path from South side"] = "從南邊的路徑"
L["Enter at top of temple"] = "進入神廟的頂部"
-- HF xxxxx - Trésors de Rade de Tiragarde
L["Ride the Guardian"] = "騎乘守衛者"
L["In Boralus, on Stomsong Monastary"] = "在伯拉勒斯里，斯托頌修道院"
L["Teleport here from Stormsong, pick up the gem"] = "從斯托頌傳送到這里，拿起寶石"
L["Kill pirates in Freehold until the map drops"] = "擊殺海盜掉落"
L["Entrance to the underwater cave"] = "水下洞穴的入口"
L["Read Damp Scrolls; in the underwater cave, from the monastary"] = "閱讀潮濕的卷軸；從修道院過去的水下洞穴"
L["Read Damp Scrolls; underground"] = "閱讀潮濕的卷軸；地下室"
L["Read Damp Scrolls; upstairs"] = "閱讀潮濕的卷軸；樓上"
L["Read Damp Scrolls"] = "閱讀潮濕的卷軸"
L["Ominous Altar; use it, get teleported, pick up the gem"] = "不祥的祭壇；使用它進行傳送，拿起寶石"
-- HF xxxxx - Trésors de Drustvar
L["Left Down Up Right"] = "左下上右"
L["Right Up Left Down"] = "右上左下"
L["Click on Witch Torch"] = "點擊巫術火把"
L["Get keys from Gorging Raven"] = "從貪吃的烏鴉那里獲得鑰匙"
L["Left Right Down Up"] = "左右下上"
-- HF xxxxx - Trésors de Vallée Chantorage
L["On roof"] = "在屋頂上"
L["Top shelf inside shed"] = "棚子里上方的架子上"
L["Climb ladder onto ship"] = "爬梯子上船"
L["Under ship"] = "在船下方"
L["Under platform"] = "在臺子下"
L["Jump onto platform"] = "跳到臺子上"
L["Behind pillar"] = "在柱子后面"
-- Rares ------------------------------------------------------------
L["Shares spawn timer with Azuresail the Ancient and Kil'Tawan"] = "與雙帆龍藍帆和魔暴龍王科塔爾共享刷新時間"
L["Shares spawn timer with Thunderfoot and Kil'Tawan"] = "與雷龍雷腳和魔暴龍王科塔爾共享刷新時間"
L["South of Savagelands"] = "薩維格蘭南部"
L["Can be found near the road in the grass"] = "能夠在草地附近找到路"
L["South of the Nesingwary's Trek windrider"] = "在奈辛瓦里飛行點的南側"
L["Fighting Ten'gor at crossroad"] = "在路口與恐角龍戰斗"
L["On the road from Zeb'ahari to Tal'gurub"] = "從澤布阿里到塔爾格拉布的路上"
L["Flying close to the road from Vol'dun to Zuldazar"] = "在沃頓到祖達薩的路附近飛行"
L["Ride to Roan Berthold in Southwind Station, follow the road"] = "在南風站騎乘黑白雜色的馬，沿著路走"
L["Inside skeleton under the sand"] = "埋在沙里的骨架下"
L["Hillside above the cave"] = "山洞上的斜坡"
L["Pick one to fight; Dagger from Longfang, mail gloves from Henry"] = "挑選一個戰斗；龍方的匕首，亨利的裝甲拳套"
-- HF 13027 - Récolte de champignons
L["On the beach, between trees"] = "在海灘上，在樹之間"
L["South of Heart of Darkness. Entrance is from the north side of Xal'vor ruins"] = "在黑暗之心的南邊。入口在廢墟的北邊。"
L["In cave, entrance at 73.2 49.7"] = "在山洞里，入口在73.2 49.7"
L["Shrouded Shore, on the hill"] = "被遮擋的海岸，在山上"
-- HF 13028 - Triste sot
L["Lost Spawn of Krag'wa 1"] = "迷路的卡格瓦子嗣 1"
L["Lost Spawn of Krag'wa 2"] = "迷路的卡格瓦子嗣 2"
L["Lost Spawn of Krag'wa 3"] = "迷路的卡格瓦子嗣 3"
L["Lost Spawn of Krag'wa 4"] = "迷路的卡格瓦子嗣 4"
L["Lost Spawn of Krag'wa 5"] = "迷路的卡格瓦子嗣 5"
L["Lost Spawn of Krag'wa 6"] = "迷路的卡格瓦子嗣 6"
L["Lost Spawn of Krag'wa 7"] = "迷路的卡格瓦子嗣 7"
L["Lost Spawn of Krag'wa 8"] = "迷路的卡格瓦子嗣 8"
L["Lost Spawn of Krag'wa 9"] = "迷路的卡格瓦子嗣 9"
L["Lost Spawn of Krag'wa 10"] = "迷路的卡格瓦子嗣 10"
-- HF 13046 - Les collines de l'appétit
L["Buy %s from %s "] = "從 %s 購買 %s"
L["to Brennadam"] = "前往布倫納丹"
L["Use Cooking for %s"] = "對 %s 使用烹飪"
L["The recipe %s and loot on %s to Waycrest Manor"] = "在維克雷斯莊園獲得 %s 配方"
-- HF 13051 - Légendes des Eaugures
L["Near the waterfall"] = "瀑布附近"
L["On top of the hill"] = "在山頂上"
L["Near the lake"] = "在湖附近"
L["On top of the island"] = "在島上"
L["Up the mountain right of Warfang Hold"] = "在戰牙要塞右邊的山上"
L["Up the mountain left of Warfang Hold"] = "在戰牙要塞左邊的山上"
L["Near the Shrine of the Storm entrance"] = "風暴神殿入口附近的神龕"
-- HF 13057 - Les chants de la mer
L["On the fireplace mantel"] = "在壁爐臺上"
L["Behind the Jay the Tavern Bard"] = "在酒館吟游詩人杰伊背后"
-- HF 13082 - Du neuf avec du vieux
L["Near the cliff under the trees west of Arom's Stand flight master."] = "在阿羅姆之臺飛行點西邊的懸崖樹下"
L["Between the rocks mid level of the waterfall"] = "在瀑布中段的石縫中"
L["On the mountain north of Fallhaven in the pile of bones."] = "在蕭灣鎮北邊山上的骨堆里"
L["In the tree trunk from the south side"] = "在南邊的樹干里"
------------------------------------------------------------------Arathi
L["Doom's Howl"] = true
L["Alliance only"] = "僅限聯盟"
L["Branchlord Aldrus"] = true
L["Overseer Krix"] = true
L["Yogursa"] = true
L["Ragebeak"] = true
L["Burning Goliath"] = true
L["Cresting Goliath"] = true
L["Fozruk"] = true
L["Plaguefeather"] = true
L["Rumbling Goliath"] = true
L["Skullripper"] = true
L["Thundering Goliath"] = true
L["Venomarus"] = true
L["Molok the Crusher"] = true
L["Kor'gresh Coldrage"] = true
L["Echo of Myzrael"] = true
L["Geomancer Flintdagger"] = true
L["Beastrider Kama"] = true
L["Darbel Montrose"] = true
L["Doomrider Helgrim"] = true
L["Foulbelly_cave"] = "Cave entrance to Foulbelly"
L["Foulbelly"] = true
L["Horrific Apparition"] = true
L["Kovork_cave"] = "Cave entrance to Kovork"
L["Kovork"] = true
L["Man-Hunter Rog"] = true
L["Nimar the Slayer"] = true
L["Singer"] = true
L["Zalas Witherbark"] = true
L["Ruul Onestone"] = true
L["Knight-Captain Aldrin"] = true
L["Horde only"] = "僅限部落"
L["The Lion's Roar"] = true
L["Kor'gresh Coldrage_cave"] = "Cave entrance to Kor'gresh Coldrage"
L["Geomancer Flintdagger_cave"] = "Cave entrance to Geomancer Flintdagger"
L["Zalas Witherbark_cave"] = "Cave entrance to Zalas Witherbark"
L["Overseer Krix_cave"] = "Cave entrance to Overseer Krix"
L["(Mount known)"] = "(|cFF00FF00已獲得坐騎|r)"
L["(Mount missing)"] = "(|cFFFF0000未獲得坐騎|r)"
L["(Toy known)"] = "(|cFF00FF00已獲得玩具|r)"
L["(Toy missing)"] = "(|cFFFF0000未獲得玩具|r)"
L["(itemLinkGreen)"] = "(|cFF00FF00%s|r)"
L["(itemLinkRed)"] = "(|cFFFF0000%s|r)"
L["Retrieving data ..."] = "正在檢索數據…"
L["Sorry, no groups found!"] = "Sorry, no groups found!"
L["Search in Quests"] = "Search in Quests"
L["Groups found:"] = "Groups found:"
L["Create new group"] = "Create new group"
L["context_menu_title"] = "HandyNotes 恩若司的幻象"
L["context_menu_check_group_finder"] = "Check group availability"
L["context_menu_reset_rare_counters"] = "Reset group counters"
L["context_menu_add_tomtom"] = "加入到TomTom"
L["context_menu_hide_node"] = "隱藏此節點"
L["context_menu_restore_hidden_nodes"] = "恢復所有隱藏節點"
L["Arathi"] = true
L["options_icon_settings"] = "圖示設定"
L["options_icon_settings_desc"] = "圖標設置"
L["options_icons_treasures"] = "寶藏圖示"
L["options_icons_treasures_desc"] = "寶箱圖標"
L["options_icons_rares"] = "稀有圖示"
L["options_icons_rares_desc"] = "稀有怪圖標"
L["options_icons_caves"] = "洞穴圖示"
L["options_icons_caves_desc"] = "Cave Icons"
L["options_icons_pet_battles"] = "戰寵圖示"
L["options_icons_pet_battles_desc"] = "寵物對戰圖標"
L["options_scale"] = "縮放"
L["options_scale_desc"] = "1 = 100%"
L["options_opacity"] = "透明度"
L["options_opacity_desc"] = "0 = 透明, 1 = 不透明"
L["options_visibility_settings"] = "可視性"
L["options_visibility_settings_desc"] = "可見項設置"
L["options_toggle_treasures"] = "寶藏"
L["options_toggle_rares"] = "稀有"
L["options_toggle_battle_pets"] = "戰寵"
L["options_toggle_npcs"] = "NPC"
L["options_toggle_caves"] = "洞穴"
L["options_general_settings"] = "一般"
L["options_general_settings_desc"] = "常規設置"
L["options_toggle_alreadylooted_rares"] = "顯示已獲得戰利品的稀有怪"
L["options_toggle_alreadylooted_rares_desc"] = "無論是否獲得戰利品，都顯示所有的稀有怪"
L["options_toggle_alreadylooted_treasures"] = "顯示已打開的寶箱"
L["options_toggle_alreadylooted_treasures_desc"] = "無論是否已經打開過，都顯示所有的寶箱"
L["options_tooltip_settings"] = "工具提示"
L["options_tooltip_settings_desc"] = "工具提示"
L["options_toggle_show_loot"] = "顯示戰利品"
L["options_toggle_show_loot_desc"] = "在工具提示中加入戰利品資訊"
L["options_toggle_show_notes"] = "顯示註記"
L["options_toggle_show_notes_desc"] = "在可用的工具提示中加入有用的註記"
L["options_toggle_show_debug"] = "偵錯"
L["options_toggle_show_debug_desc"] = "顯示偵錯內容"
L["options_toggle_hideKnowLoot"] = "若獲得所有的戰利品，則隱藏稀有怪"
L["options_toggle_hideKnowLoot_desc"] = "無需求了，就別殺別人了"
L["Shared"] = "Shared"
L["Somewhere"] = "Somewhere"
L["Dagger"] = true
L["Allow left click to open journal to dungeon or raid"] = "允許使用左鍵打開地城或團隊副本的冒險指南"
L["Allow right click to create waypoints with TomTom"] = "允許使用右鍵建立 TomTom 導引箭頭"
L["Continent Alpha"] = "大陸地圖圖示透明度"
L["Continent Scale"] = "大陸地圖圖示縮放大小"
L["Don't show discovered dungeons"] = "不要顯示已發現的地城"
L["Enable TomTom integration"] = "啟用 TomTom 整合"
L["Filter Options"] = "過濾選項"
L["Hide all BfA nodes from the map"] = "隱藏地圖上所有決戰艾澤拉斯的副本圖示"
L["Hide all Broken Isle nodes from the map"] = "隱藏地圖上所有破碎群島的副本圖示"
L["Hide all Cataclysm nodes from the map"] = "隱藏地圖上所有浩劫與重生的副本圖示"
L["Hide all Draenor nodes from the map"] = "隱藏地圖上所有德拉諾的副本圖示"
L["Hide all Northrend nodes from the map"] = "隱藏地圖上所有北裂境的副本圖示"
L["Hide all Outland nodes from the map"] = "隱藏地圖上所有外域的副本圖示"
L["Hide all Pandaria nodes from the map"] = "隱藏地圖上所有潘達利亞的副本圖示"
L["Hide all Vanilla nodes from the map"] = "隱藏地圖上所有艾澤拉斯的副本圖示"
L["Hide Battle for Azeroth"] = "隱藏決戰艾澤拉斯"
L["Hide Broken Isles"] = "隱藏破碎群島"
L["Hide Cataclysm"] = "隱藏浩劫與重生"
L["Hide Draenor"] = "隱藏德拉諾"
L["Hide Instances"] = "隱藏副本"
L["Hide Northrend"] = "隱藏北裂境"
L["Hide Outland"] = "隱藏外域"
L["Hide Pandaria"] = "隱藏潘達利亞"
L["Hide Vanilla"] = "隱藏艾澤拉斯"
L["Invert Lockout"] = "反向顯示已擊殺"
L["Journal Integration"] = "啟用冒險指南整合"
L["Lockout Alpha"] = "已擊殺透明度"
L["Lockout Gray Icon"] = "已擊殺灰色圖示"
L["Lockout Options"] = "首領已擊殺選項"
L["Lockout Tooltip"] = "已擊殺滑鼠提示"
L["Show dungeon locations on the map"] = "在地圖上顯示5人地城的位置"
L["Show Dungeons"] = "顯示地城"
L["Show icons on continent map"] = "在大陸地圖上顯示圖示"
L["Show lockout information on tooltips"] = "在滑鼠提示中顯示首領已擊殺的資訊"
L["Show Mixed"] = "都顯示"
L["Show mixed (dungeons + raids) locations on the map"] = "在地圖上顯示地城和團隊副本的位置"
L["Show on Continent"] = "顯示於大陸地圖"
L["Show raid locations on the map"] = "在地圖上顯示團隊副本的位置"
L["Show Raids"] = "顯示團隊"
L["The alpha of dungeons and raids that are locked to any extent"] = "任何難度的地城和團隊副本首領已擊殺的透明度"
L["The alpha of the icons shown on the continent map"] = "大陸地圖上的圖示透明度"
L["The alpha of the icons shown on the zone map"] = "區域地圖上的圖示透明度"
L["The scale of the icons shown on the continent map"] = "大陸地圖上的圖示大小"
L["The scale of the icons shown on the zone map"] = "區域地圖上的圖示大小"
L["This will check for legion and bfa dungeons that have already been discovered. THIS IS KNOWN TO CAUSE TAINT, ENABLE AT OWN RISK."] = "將會檢查軍臨天下和決戰艾澤拉斯已發現的地城。警告: 此功能已知會引起程式碼汙染的錯誤，啟用時請自行承擔風險。"
L["Turn mixed icons grey when ANY dungeon or raid listed is locked"] = "列出的任何地城或團隊已擊殺時，將混合的圖示顯示為灰色。"
L["Use a different alpha for dungeons and raids that are locked to any extent"] = "使用不同的透明度來顯示首領已擊殺的地城和團隊副本 (任何難度)"
L["Use gray icon for dungeons and raids that are locked to any extent"] = "使用灰色圖示來顯示首領已擊殺的地城和團隊副本 (任何難度)"
L["Use Lockout Alpha"] = "使用已擊殺透明度"
L["Zone Alpha"] = "區域地圖圖示透明度"
L["Zone Scale"] = "區域地圖圖示縮放大小"
-------------------------------------------------------MoleMachine
L["Aerie Peak"] = "鷹巢山"
L["Argent Tournament Grounds"] = "銀白聯賽場地"
L["Blackrock Foundry Overlook"] = "黑石鑄造廠眺望"
L["Broken Shore"] = "破碎群島"
L["Elemental Plateau"] = "元素高原"
L["Fel Pits"] = "惡魔深坑"
L["Fire Plume Ridge"] = "火羽山"
L["Inside Blackrock Mountain"] = "黑石山裡面"
L["Ironforge"] = "鐵爐堡"
L["Mole Machine"] = "鑽地機"
L["Neltharion's Vault"] = "奈薩里奧巢穴"
L["Nethergarde Keep"] = "守望堡"
L["One Keg"] = "獨罈集"
L["Ruby Dragonshrine"] = "晶紅龍殿"
L["Shadowforge City"] = "暗爐城"
L["Stormstout Brewery"] = "風暴烈酒酒坊"
L["Stormwind"] = "暴風城"
L["The Great Divide"] = "大裂口"
L["Throne of Flame"] = "烈焰王座"

L["Warfronts"] = true
L["Darkshore"] = true
L["Amberclaw"] = true
L["Shattershard"] = true
L["Scalefiend"] = true
L["Mrggr'marr"] = true
L["Aman"] = true
L["Hydrath"] = true
L["Soggoth the SLitherer"] = true
L["Twilight Prophet Graeme"] = true
L["Athrikus Narassin"] = true
L["Commander Ral'esh"] = true
L["Glimmerspine"] = true
L["Madfeather"] = true
L["Granokk"] = true
L["Stonebinder Ssra'vess"] = true
L["Cyclarus"] = true
L["Gren Tornfur"] = true
L["Alash'anir"] = true
L["Conflagros"] = true
L["Grimhorn"] = true
L["Onu"] = true
L["Shadowclaw"] = true
L["Thelar Moonstrike"] = true
L["Sapper Odette"] = true
L["Blackpaw"] = true
L["Athil Dewfire"] = true
L["Zim'kaga"] = true
L["Moxo the Beheader"] = true
L["Commander Drald"] = true
L["Orwell Stevenson"] = true
L["Burninator Mark V"] = true
L["Croz Bloodrage"] = true
L["Agathe Wyrmwood"] = true
L["Ivus the Forest Lord"] = true
L["Ivus the Decayed"] = true
L["Astravar Harbor"] = "艾斯特瓦港"
L["Evermoon Terrace"] = "永月露臺"
L["Falanaar"] = "法拉納爾"
L["Felsoul Hold"] = "魔魂堡"
L["Lunastre Estate"] = "路納斯特莊園"
L["Moon Guard (entrance)"] = "月之守衛 (入口)"
L["Moon Guard Stronghold"] = "月之守衛要塞"
L["Ruins of Elune'eth"] = "伊露恩斯遺址"
L["Sanctum of Order"] = "秩序聖所"
L["Sanctum of Order (entrance)"] = "秩序聖所 (入口)"
L["Tel'anor"] = "泰爾亞諾"
L["Twilight Vineyards"] = "暮光葡萄園"
L["Waning Crescent"] = "弦月旅店"
-- chests
L["Moss-Covered Chest"] = true
L["Sturdy Chest"] = true
L["Smoldering Chest"] = true
L["Skull-Covered Chest"] = true
L["Blazing Chest"] = true
-- notes
L["On a treestump"] = true
L["In the shipwreck of Cpt. Zvezdan"] = true
L["On the top of the cliff. Use the Highwind Albatross"] = true
L["Inside the Mysterious Den. Use one of objects from Legends of the Past"] = true
L["Inside Cavern of Lost Spirits (entrance at 43.2, 41.3)"] = true
-- tooltip
L["Completed"] = true
-- buttons
-- options
L["Timeless Treasures locations."] = 'Locations of the chests for \"Treasure, Treasure Everywhere\".'
L["These settings control the visibility of the icons."] = "These settings control the visibility of the icons.\n\n"
L["Show completed"] = "Show completed"
L["Show icons for treasures you have already got."] = "Show icons for chests you have already opened."
L["Show Moss-Covered Chests"] = "Show Moss-Covered Chests"
L["Show not completed Moss-Covered Chests"] = "Show not completed Moss-Covered Chests"
L["Remove Icon Border"] = "Remove Icon Border"
L["Change the size of the icons."] = "Change the size of the icons."
L["Change the transparency of the icons."] = "Change the transparency of the icons."
L["These settings control the look of the icons."] = "\n\nThese settings control the look of the icons.\n\n"
L["Change Icon"] = "Enter the full texture path \ni.e. |cffFFFF00Interface\\ICONS\\inv_box_01|r"
L["OptionsDescription"] = "永恒岛稀有精英位置显示"
L["OptionsArgsDescription"] = "调整图标外观"
L["OptionsIconScaleName"] = "图标大小"
L["OptionsIconScaleDescription"] = "图标的大小"
L["OptionsIconAlphaName"] = "图标透明度"
L["OptionsIconAlphaDescription"] = "图标的透明度"
L["EmeralGander"] = "翠羽公鹤"
L["EmeralGanderDrop"] = "风翎鹤羽"
L["EmeralGanderInfo"] = "在天神庭院周围有许多刷新点。"
L["IronfurSteelhorn"] = "铁鬃铜角牛"
L["IronfurSteelhornDrop"] = "一簇牦牛毛"
L["ImperialPython"] = "帝王巨蟒"
L["ImperialPythonDrop"] = "致死小蝰蛇"
L["GreatTurtleFuryshell"] = "怒壳巨龟"
L["GreatTurtleFuryshellDrop"] = "硬化之壳"
L["GreatTurtleFuryshellInfo"] = "在西海岸巡逻。"
L["GuchiSwarmbringer"] = "虫群先锋古赤"
L["GuchiSwarmbringerDrop"] = "古赤的蚕宝宝"
L["GuchiSwarmbringerInfo"] = "在老酒湾附近刷新。"
L["Zesqua"] = "泽泉"
L["ZesquaDrop"] = "降雨之石"
L["ZesquaInfo"] = "在老酒湾的海岸东边。"
L["ZhuGonSour"] = "泛酸的筑汞"
L["ZhuGonSourDrop"] = "酒灵臭臭"
L["ZhuGonSourInfo"] = "在老酒湾刷新的稀有事件，完成后可看见稀有精英泛酸的筑汞。"
L["Karkanos"] = "卡卡诺斯"
L["KarkanosDrop"] = "一大包永恒铸币"
L["KarkanosInfo"] = "码头会刷新钓手，与之对话可召唤卡卡诺斯。"
L["Chelon"] = "蛰龙"
L["ChelonDrop"] = "硬化之壳"
L["ChelonInfo"] = "蛰龙刷新时为龟壳，点击后即可召唤出蛰龙。"
L["Spelurk"] = "斯普鲁克"
L["SpelurkDrop"] = "被诅咒的护身符"
L["SpelurkInfo"] = "秘密巢穴洞口被塌方覆盖，进入的玩家需要点击左边石头旁的巨锤以砸开塌方，同时斯普鲁克刷新。法师可以闪现进去用里面的巨锤砸开塌方。"
L["Cranegnasher"] = "噬鹤者"
L["CranegnasherDrop"] = "新鲜的追猎者之皮"
L["CranegnasherInfo"] = "需要召唤。 地上出现可调查的嗜鱼鹤尸体时，从南边拉一只嗜鱼鹤过来它就会跳下来。"
L["Rattleskew"] = "响骨 - 扎维兹坦船长"
L["RattleskewDrop"] = "扎维兹坦船长遗失的小腿"
L["RattleskewInfo"] = "随机事件“藤壶号之战”：东南部半艘沉船(60.6, 87.2)的甲板上出现扎维兹坦船长及其手下剑客时，击败围攻它们的亡灵水手后刷新。"
L["MonstrousSpineclaw"] = "凶暴钳爪蟹"
L["MonstrousSpineclawDrop"] = "钳爪小螃蟹"
L["MonstrousSpineclawInfo"] = "海边所有可能的钳爪蟹刷新点。"
L["SpiritJadefire"] = "玉火之灵"
L["SpiritJadefireDrop"] = "发光的绿色灰烬"
L["SpiritJadefireDrop2"] = "玉火炎灵"
L["SpiritJadefireInfo"] = "孤魂岩洞内刷新。"
L["Leafmender"] = "剪叶者"
L["LeafmenderDrop"] = "灰叶小林精"
L["LeafmenderInfo"] = "永恒岛下方蹈火者上方精英野牛人区。"
L["Bufo"] = "布佛"
L["BufoDrop"] = "幼年巨口娃"
L["BufoInfo"] = "在有很多巨口娃的区域刷新。"
L["Garnia"] = "加尼亚"
L["GarniaDrop"] = "红玉小水滴"
L["GarniaInfo"] = "在红玉湖刷新，只能坐信天翁上去。"
L["Tsavoka"] = "查沃卡"
L["TsavokaDrop"] = "新鲜的追踪者之皮"
L["TsavokaInfo"] = "在查沃卡巢穴中刷新。"
L["Stinkbraid"] = "斯汀克布莱德"
L["StinkbraidInfo"] = "右下海面上的海盗船上。"
L["RockMoss"] = "石苔"
L["RockMossDrop"] = "金苔藓"
L["RockMossInfo"] = "孤魂岩洞深处。"
L["WatcherOsu"] = "斥候奥苏"
L["WatcherOsuDrop"] = "灰烬之石"
L["WatcherOsuInfo"] = "蹈火者小径。"
L["JakurOrdon"] = "神战士迦库尔"
L["JakurOrdonDrop"] = "警告标志"
L["JakurOrdonInfo"] = "蹈火者废墟悬崖边缘处。"
L["ChampionBlackFlame"] = "黑火勇士"
L["ChampionBlackFlameDrop"] = "黑火匕首"
L["ChampionBlackFlameDrop2"] = "一大袋草药"
L["ChampionBlackFlameInfo"] = "蹈火者小径，不停的沿着道路巡逻。黑火勇士是3个一组的野牛人。"
L["Cinderfall"] = "落烬"
L["CinderfallDrop"] = "坠焰"
L["CinderfallInfo"] = "断桥处。"
L["UrdurCauterizer"] = "烙印者乌都尔"
L["UrdurCauterizerDrop"] = "日落之石"
L["UrdurCauterizerInfo"] = "斡耳朵神殿外围墙边。"
L["FlintlordGairan"] = "燧石领主铠兰"
L["FlintlordGairanDrop"] = "斡耳朵死亡之钟"
L["FlintlordGairanInfo"] = "斡耳朵神殿周围有很多刷新点。"
L["Huolon"] = "惑龙"
L["HuolonDrop"] = "雷霆玛瑙云端祥龙的缰绳"
L["HuolonInfo"] = "在蹈火者之径附近的天空中飞翔。"
L["Golganarr"] = "高戈纳尔"
L["GolganarrDrop"] = "古怪的抛光石"
L["GolganarrDrop2"] = "一堆闪亮的石头"
L["GolganarrInfo"] = "就在这附近刷新。"
L["Evermaw"] = "吞天"
L["EvermawDrop"] = "雾气缭绕的幽魂灯笼"
L["EvermawInfo"] = "此标记不是确切的位置，因为这货沿着海岸一直在游。"
L["DreadShipVazuvius"] = "幽灵船瓦组维斯号"
L["DreadShipVazuviusDrop"] = "迷时水手结晶"
L["DreadShipVazuviusInfo"] = "需要在海边的墓碑处使用击杀稀有吞天后获得的物品雾气缭绕的幽魂灯笼才会出现。"
L["ArchiereusFlame"] = "烈焰祭司阿克鲁斯"
L["ArchiereusFlameDrop"] = "远古知识药剂"
L["ArchiereusFlameInfo"] = "在斡耳朵圣殿内刷新，所以没有橙色披风的玩家只能在挑战者之石处使用挑战卷轴。"
L["RattleskewDrop2"] = "工艺图:骷髅雕文"
----------------------------------- MECHAGON ----------------------------------
L["options_title_Mechagon"] = "機械岡 & 納沙塔爾"
L["context_menu_title_Mechagon"] = "機械岡 & 納沙塔爾";
L["Mechagon"] = "機械岡"
L["avenger_note"] = "當奧格索普?奧布諾提斯是訪客時，殺死OOX-Fleetfoot/MG (區域滿地跑)來重生。"
L["beastbot_note"] = "在帕斯卡K1N6型製作一個［野獸機器人動力包］來啟動。"
L["cogstar_note"] = "殺死區域內任何地方的升級版哨衛，直到他傳送進來加強小怪。"
L["crazed_trogg_note"] = "在邦多的機械廠裡使用噴塗機，塗滿油漆的氣囊或機器人，用他大喊的顏色塗上自己。"
L["deepwater_note"] = "在帕斯卡K1N6型製作一個［百噚誘餌］來召喚。"
L["doppel_gang"] = "分身"
L["doppel_note"] = "從每日任務＂輪狂的建造狂熱＂獲得［減壓閥］，與其他兩名玩家一起啟動。"
L["drill_rig"] = "需要鑽探機"
L["foul_manifest_note"] = "連接水中的電塔到外圍電塔通電，然後到旁邊山坡上找到開關按下就會出現。"
L["furor_note"] = '在每日任務 "來自諾達希爾的協助" 期間，點擊小藍色蘑菇直到出現。'
L["killsaw_note"] = "在飛逝森林的任何地方出現，似乎殺死鋸刃伐木機器人後比較容易出現。不會在風險投資公司在森林裡的時候出現，那時候沒有伐木機器人。"
L["leachbeast_note"] = "使用［發熱蒸發器線圈］啟動天氣改變裝置，天氣轉為下雨後，擊殺一定數量的濾液怪出現。"
L["nullifier_note"] = "使用藍色卡片－[遠距迴路旁通器] 或是DNT-碰撞轉移裝置駭入啟動。前者為廢料王掉落，後者為鑽探機JD41與JD99的小怪掉落。"
L["scrapclaw_note"] = "離岸在水中。"
L["sparkqueen_note"] = "當每日任務＂有蟲.好多蟲!＂期間，殺死一定數量蜘蛛出現。"
L["rusty_note"] = "在帕斯卡K1N6型上製作一個［個人時光移轉裝置］，以進入不同的未來。只有當克羅米不是訪客時才會出現。"
L["vaultbot_note"] = "風箏到邦多的機械廠的特斯拉線圈，或在帕斯卡K1N6型上製作一個保險庫機器人鑰匙來直接打開。"
L["iron_chest"] = "鐵潮帶鎖箱"
L["mech_chest"] = "機械箱"
L["msup_chest"] = "機械補給箱"
L["rust_chest"] = "老舊生鏽箱子"
L["iron_chest_note"] = "開啟鐵潮帶鎖箱的鑰匙從西湧列島小怪掉落。"
L["msup_chest_note"] = "開啟機械補給箱的鑰匙從西湧列島小怪掉落。"
L["rust_chest_note"] = "開啟老舊生鏽箱子的鑰匙從西湧列島小怪掉落。"
L["rec_rig"] = "廢料回收機"
L["rec_rig_note"] = "要啟動困難模式，使用超級對撞機武器來將所有輻射元素轉換為不穩定輻射元素。寵物可以在兩種難度中獲得。"
L["options_icons_mech_chest"] = "機械化箱"
L["options_icons_mech_chest_desc"] = "顯示機械化箱子的位置。有10個獨特的箱子可以每天洗一次，每個箱子有4-5個產卵位置。位置按顏色分組。"
L["options_icons_locked_chest"] = "鎖定箱子"
L["options_icons_locked_chest_desc"] = "在西湧列島中顯示上鎖箱子的位置。"
L["options_icons_recrig"] = "廢料回收機"
L["options_icons_recrig_desc"] = "顯示廢料回收機的位置以及事件獎賞。"
----------------------------------- NAZJATAR ----------------------------------
L["Nazjatar"] = "納沙塔爾"
L["naz_intro_note"] = "完成入門任務鏈，解鎖Nazjatar上的rares，寶藏和世界任務。"
L["alga_note"] = "注意: 被四個小怪遮掩！"
L["allseer_note"] = "在卡美伊爾低層的任何地方出現。"
L["anemonar_note"] = "在它上方擊殺巨大的擎天魟來啟動。"
L["avarius_note"] = "使用鹵石鎬收集並將彩色晶體放在基座上。 你不必是一個礦工！"
L["banescale_note"] = "有很小的機率在殺死群母後立即出現。"
L["elderunu_note"] = "在卡美伊爾高層的任何地方出現。"
L["gakula_note"] = "驅趕血鳍蝌蚪直到它出現。"
L["glimmershell_note"] = "有小機率出現在微光殼巨蟹的位置。"
L["kelpwillow_note"] = "使用棱彩水晶魅惑［淤泥蛞蝓］後帶給它來啟動。"
L["lasher_note"] = "在土壤中種植發芽的種子並餵養蒼蠅。"
L["matriarch_note"] = "與另外兩位族母共享重生計時器。"
L["needle_note"] = "通常出現在［女王之門］區域。"
L["oronu_note"] = "到沉默市場找到NPC購買［溺水幼鷹獸］寵物帶著它靠近後就可啟動。"
L["rockweed_note"] = "殺死整個區域的失落的Algan和Wayward Algan直到他出現。 建議使用團隊，因為這可能是一個長期的苦工作。"
L["sandcastle_note"] = "使用顯現石在區域內的任何地方顯露寶箱直到它出現。"
L["tidelord_note"] = "殺死三個艾薩利塑能師以及招喚的被釋放的狂潮直到浪潮領主被召喚出來。"
L["tidemistress_note"] = "點擊未受干擾的樣本直到她出現。"
L["urduu_note"] = "在它面前重疊擊殺［鹿角暗礁行者］後來啟動。"
L["voice_deeps_notes"] = "使用脫下來的殼來衝破此岩石。"
L["vorkoth_note"] = "把餌食扔進池中直到它出現。"
L["area_spawn"] = "在周邊地區出現。"
L["cora_spawn"] = "在珊瑚林的任何地方出現。"
L["cave_spawn"] = "在洞穴中出現。"
L["east_spawn"] = "在區域的東半邊任何地方出現。"
L["ucav_spawn"] = "在水下的洞穴出現。"
L["zone_spawn"] = "在整個區域出現。"
L["supply_chest"] = "戰爭補給箱"
L["assassin_looted"] = "當為刺客時可以拾取。"
L["arcane_chest"] = "祕法寶箱"
L["glowing_chest"] = "發光的祕法寶箱"
L["arcane_chest_01"] = "在一些海藻下。"
L["arcane_chest_02"] = "在建築內部的上層"
L["arcane_chest_03"] = "在第二層。"
L["arcane_chest_04"] = "在瀑布上方的水中。"
L["arcane_chest_05"] = "在廢墟中。"
L["arcane_chest_06"] = ""
L["arcane_chest_07"] = "在洞穴的後面。入口位於贊季爾沙灘東邊。"
L["arcane_chest_08"] = "藏在一些海星下面。"
L["arcane_chest_09"] = "在珍珠殼爬行者(暫譯)後面的一個洞穴裡。"
L["arcane_chest_10"] = "在一個脫下來的殼下面。"
L["arcane_chest_11"] = "在山丘的頂部。"
L["arcane_chest_12"] = "在瀑布的頂部。"
L["arcane_chest_13"] = "在懸崖的頂部，在樹後面。"
L["arcane_chest_14"] = "在伊露恩諾神殿內部。"
L["arcane_chest_15"] = "在建築物的右側。"
L["arcane_chest_16"] = "在水下的洞穴，入口在南方。"
L["arcane_chest_17"] = "在瀑布的頂部。"
L["arcane_chest_18"] = "在路徑下方的一個洞穴裡。"
L["arcane_chest_19"] = "在岩石拱門的頂部。 使用滑翔翼（或是飛行）"
L["arcane_chest_20"] = "在山的頂部。"
L["glowing_chest_1"] = "在水下洞穴的後面，防衛鐵塔。"
L["glowing_chest_2"] = "解開線條。"
L["glowing_chest_3"] = "在洞穴的後面。防衛鐵塔。"
L["glowing_chest_4"] = "消掉三個紅色符文。"
L["glowing_chest_5"] = "在洞穴，防衛鐵塔。"
L["glowing_chest_6"] = "解開線條。"
L["glowing_chest_7"] = "消掉四個藍色符文。"
L["glowing_chest_8"] = "在屋頂上。防衛鐵塔。"
L["slimy_cocoon"] = "軟泥的卵"
L["ravenous_slime_note"] = "使用棱彩水晶控制小動物餵養軟泥。重複五天，直到它產生一個帶有寵物的卵。軟泥將一直持續到下一周重置。"
L["slimy_cocoon_note"] = "一隻寵物準備從卵中收集！ 如果在您的階段它沒有出現，那麼卵的冷卻時間就會消失。 更改階段或稍後再回來查看。"
L["cat_figurine"] = "水晶貓雕像"
L["cat_figurine_01"] = "在一個水下洞穴。雕像在露天的地板上。入口在東邊。"
L["cat_figurine_02"] = "在附近瀑布下的一個洞穴裡。 雕像在牆上的海星下面。"
L["cat_figurine_03"] = "在一個水下洞穴。雕像被藏在某些破碎的貝殼下。"
L["cat_figurine_04"] = "在一個水下洞穴。雕像在露天的地板上。"
L["cat_figurine_05"] = "在一個小洞穴。雕像隱藏在地板上的植物後面。"
L["cat_figurine_06"] = "在一個充滿敵對的礁石行者的水下洞穴中。 小雕像在牆上。 入口在北方。"
L["cat_figurine_07"] = "在一個小洞穴。雕像在一些珊瑚的牆上。"
L["cat_figurine_08"] = "在一個小洞穴。躲避祕法圈。 小雕像在後面的高大的岩石上。"
L["cat_figurine_09"] = "在一個水下洞穴。雕像位於天花板的岩石拱門上。"
L["cat_figurine_10"] = "在路徑下方的一個洞穴裡。 雕像在三個桶之間。"
L["mardivas_lab"] = "瑪爾迪瓦斯實驗室"
L["no_reagent"] = "不使用水晶"
L["swater"] = "小深海"
L["gwater"] = "大深海"
L["sfire"] = "小火炎"
L["gfire"] = "大火炎"
L["searth"] = "小土岩"
L["gearth"] = "大土岩"
L["murloco"] = "莫落哥"
L["tentacle_taco"] = "出售 "..ITEM_QUALITY_COLORS[4].hex.."[飢餓使者的觸手捲]|r 如果你是穿著艾薩利怒濤者斗篷。"
L["options_icons_treasures_nazj"] = "寶藏"
L["options_icons_treasures_nazj_desc"] = "顯示［尋寶追蹤者］成就的箱子位置。"
L["options_icons_slimes_nazj"] = "飢餓的軟泥"
L["options_icons_slimes_nazj_desc"] = "顯示已經餵養可以產出戰寵的四種飢餓軟泥的位置。"
L["options_icons_cats_nazj"] = "貓咪雕像"
L["options_icons_cats_nazj_desc"] = "顯示'喵出喵咪喵像'成就的水晶貓位置。"
L["options_icons_misc_nazj"] = "其他"
L["options_icons_misc_nazj_desc"] = "顯示莫洛哥的洞穴以及瑪爾迪瓦斯的實驗室的位置。"
------------------------------------ CAVES ------------------------------------
L["blindlight_cave"] = "盲光洞穴的入口。"
L["caverndark_cave"] = "洞闇恐懼洞穴的入口。"
L["chasmhaunt_cave"] = "裂谷追魂鰻洞穴的入口。"
L["shassera_cave"] = "夏瑟菈洞穴的入口。"
L["Nazjatar"] = "納沙塔爾"
L["Mechagon"] = "機械岡"
------------------------------------ GEAR -------------------------------------
L["bag"] = "背包"
L["cloth"] = "布甲"
L["leather"] = "皮甲"
L["mail"] = "鎖甲"
L["plate"] = "鎧甲"
L["cosmetic"] = "裝飾品"

L["1h_mace"] = "單手錘"
L["1h_sword"] = "單手劍"
L["1h_axe"] = "單手斧"
L["2h_mace"] = "雙手錘"
L["2h_axe"] = "雙手斧"
L["2h_sword"] = "雙手劍"
L["shield"] = "盾牌"
L["dagger"] = "匕首"
L["staff"] = "法杖"
L["fist"] = "拳套"
L["polearm"] = "長柄武器"
L["bow"] = "弓"
L["gun"] = "槍"
L["wand"] = "魔杖"
L["crossbow"] = "弩"
L["offhand"] = "副手"
L["warglaive"] = "戰刃"

L["ring"] = "戒指"
L["neck"] = "項鍊"
L["cloak"] = "披風"
L["trinket"] = "飾品"
---------------------------------- TOOLTIPS -----------------------------------
-------------------------------------------------------------------------------

L["activation_unknown"] = "啟動條件未知"
L["requirement_not_found"] = "所需位置未知"

L["Requires"] = "需要"
L["focus"] = "專注"
L["retrieving"] = "接收物品連結 ..."
L["in_cave"] = "在洞穴。"
L["in_small_cave"] = "在小洞穴。"
L["in_water_cave"] = "在水下洞穴。"
L["in_waterfall_cave"] = "在瀑布後面洞穴內。"
L["in_water"] = "在水下。"
L["hourly"] = "每小時"
L["daily"] = "每日"
L["weekly"] = "每週"
L["normal"] = "普通"
L["hard"] = "困難"
L["mount"] = "坐騎"
L["pet"] = "寵物"
L["spell"] = "法術"
L["toy"] = "玩具"
L["rep"] = "聲望"
L["completed"] = "已完成"
L["incomplete"] = "未完成"
L["known"] = "已獲得"
L["missing"] = "未獲得"
L["unobtainable"] = "無法獲得"
L["unlearnable"] = "無法解鎖"
L["defeated"] = "已擊敗"
L["undefeated"] = "未擊敗"

----------------------------------- OPTIONS -----------------------------------
L["context_menu_title_Visions"] = "恩若司的幻象"
L["options_title_Visions"] = "恩佐斯的幻象"
---------------------------------- VISIBILITY ---------------------------------

L["options_visibility_settings"] = "可視性"
L["options_general_settings"] = "一般"
L["options_show_completed_nodes"] = "顯示已完成"
L["options_show_completed_nodes_desc"] = "顯示所有的節點，即使它今天已被拾取或完成。"
L["options_toggle_hide_done_rare"] = "如果戰利品已收藏，隱藏稀有"
L["options_toggle_hide_done_rare_desc"] = "隱藏所有戰利品已收藏的稀有。"
L["options_toggle_hide_minimap"] = "隱藏小地圖上的所有圖示"
L["options_toggle_hide_minimap_desc"] = "在小地圖上隱藏此插件的所有圖示，並只在主地圖上顯示它們。"
L["options_toggle_maximized_enlarged"] = "當世界地圖時最大化時放大圖示"
L["options_toggle_maximized_enlarged_desc"] = "當世界地圖放到最大時，放大所有的圖示。"
L["options_toggle_use_char_achieves"] = "使用角色成就"
L["options_toggle_use_char_achieves_desc"] = "用此角色的成就進度來替代顯示整個帳號的進度。"
L["options_toggle_per_map_settings"] = "使用區域個別設定"
L["options_toggle_per_map_settings_desc"] = "只使用各個地圖各自獨立的切換、縮放和透明度設定"
L["options_restore_hidden_nodes"] = "恢復隱藏的節點"
L["options_restore_hidden_nodes_desc"] = "恢復所有使用右鍵選單隱藏的節點。"

L["options_icons_pet_battles_desc"] = "顯示戰寵訓練師與NPC的位置。"
L["options_icons_pet_battles"] = "戰寵"
L["options_icons_caves_desc"] = "顯示其他節點的洞穴入口。"
L["options_icons_caves"] = "洞穴"
L["options_icons_daily_chests_desc"] = "顯示寶箱位置 (每日可拾取的)。"
L["options_icons_daily_chests"] = "寶箱"
L["options_icons_misc"] = "其他"
L["options_icons_npcs"] = "NPC"
L["options_icons_other"] = "其他圖示"
L["options_icons_rares_desc"] = "顯示稀有NPC的位置。"
L["options_icons_rares"] = "稀有"
L["options_icons_supplies_desc"] = "顯示戰爭補給箱的所有可能位置。"
L["options_icons_supplies"] = "戰爭補給空投"
L["options_icons_treasures"] = "寶藏"

---------------------------------- TOOLTIP ---------------------------------

L["options_tooltip_settings"] = "工具提示"
L["options_tooltip_settings_desc"] = "工具提示"
L["options_toggle_show_loot"] = "顯示戰利品"
L["options_toggle_show_loot_desc"] = "在工具提示中加入戰利品資訊"
L["options_toggle_show_notes"] = "顯示註記"
L["options_toggle_show_notes_desc"] = "在可用的工具提示中加入有用的註記"

--------------------------------- DEVELOPMENT ---------------------------------

L["options_dev_settings"] = "開發"
L["options_dev_settings_desc"] = "開發設定"
L["options_toggle_show_debug_map"] = "偵錯地圖ID"
L["options_toggle_show_debug_map_desc"] = "顯示地圖的偵錯資訊"
L["options_toggle_show_debug_quest"] = "偵錯任務ID"
L["options_toggle_show_debug_quest_desc"] = "顯示任務變換的偵錯資訊"
L["options_toggle_force_nodes"] = "強制節點"
L["options_toggle_force_nodes_desc"] = "強制顯示全部節點"
------------------------------------ ULDUM ------------------------------------
-------------------------------------------------------------------------------

L["uldum"] = "奧丹姆"
L["uldum_intro_note"] = "完成前置引導任務鏈，以解鎖奧丹姆中的稀有物品，寶藏和攻擊任務。"

L["aqir_flayer"] = "與亞基蟲巢工人以及亞基收割者共用出生點。"
L["aqir_titanus"] = "與亞基巨怪共用出生點。"
L["aqir_warcaster"] = "與亞基虛無法師共用出生點。"
L["atekhramun"] = "壓碎附近的毒鱗幼蠍直到出現。"
L["chamber_of_the_moon"] = "在月之大廳地下。"
L["chamber_of_the_stars"] = "在眾星之間地下。"
L["chamber_of_the_sun"] = "在日陽之間裡面。"
L["dunewalker"] = "在上面的平台上點擊“太陽精華”以釋放他。"
L["friendly_alpaca"] = "餵七次羊駝吉薩爾草，以作為坐騎收藏。 在一個位置出現10分鐘，然後很久後才重生。"
L["gaze_of_nzoth"] = "與汙穢觀察者共用出生點。"
L["gersahl_note"] = "餵給友善的羊駝七次獲得坐騎。 不需要草藥學。"
L["gersahl"] = "吉薩爾草叢"
L["hmiasma"] = "餵食它周圍的軟泥，直到它啟動。"
L["kanebti"] = "從一個珠寶古墓聖甲蟲中收集一個珠寶聖甲蟲小雕像，該雕像與普通的古墓聖甲蟲共用出生點。 將雕像插入聖甲蟲聖壇以召喚稀有怪。"
L["left_eye"] = "放下全知之眼玩具的左半部分。"
L["neferset_rare"] = "這六個稀有怪在奈斐賽特具有相同的三個出生位置。 完成許多“召喚儀式”事件後，將隨機產生三個。"
L["platform"] = "出生在浮動平台頂部。"
L["single_chest"] = "此箱子僅在一個位置產生！ 如果不存在，請稍等一下，它將重新生成。"
L["spirit_cave"] = "黑暗祭儀師扎坎恩之魂的洞穴入口。"
L["tomb_widow"] = "當柱子上出現白色卵囊時，殺死隱形的蜘蛛來召喚。"
L["uatka"] = "與其他兩個玩家一起，點擊每個神秘設備。 需要來自阿瑪賽特聖匣的觸日者護符。"
L["wastewander"] = "與廢土漫遊者隊長共用出生點。"

L["amathet_cache"] = "阿瑪賽特寶箱"
L["black_empire_cache"] = "黑暗帝國寶箱"
L["black_empire_coffer"] = "黑暗帝國大寶箱"
L["infested_cache"] = "被感染的儲藏箱"
L["infested_strongbox"] = "被感染的保險箱"
L["amathet_reliquary"] = "阿瑪賽特聖匣"

L["cursed_relic"] = "需要詛咒聖物"
L["tolvir_relic"] = "需要托維爾聖物"

L["options_icons_alpaca_uldum"] = "躍毛羊駝"
L["options_icons_alpaca_uldum_desc"] = "顯示吉薩爾草叢以及友善的羊駝出生位置。"
L["options_icons_assault_events"] = "突擊事件"
L["options_icons_assault_events_desc"] = "顯示突擊事件可能的位置。"
L["options_icons_coffers"] = "上鎖的大寶箱"
L["options_icons_coffers_desc"] = "顯示上鎖的大寶箱的位置 (每次突擊只能拾取一次)。"

L["ambush_settlers"] = "打敗一波波的怪物，直到事件結束。"
L["burrowing_terrors"] = "跳起來將穴居甲蟲它們壓扁。"
L["call_of_void"] = "淨化儀式柱。"
L["combust_cocoon"] = "將土製火焰彈扔在天花板上的繭上。"
L["dormant_destroyer"] = "點擊所有虛空導管晶體。"
L["executor_nzoth"] = "殺死恩若司的執行者，然後摧毀執行者之錨。"
L["hardened_hive"] = "拿起地上的廢土火焰噴射器並燃燒所有的卵囊。"
L["in_flames"] = "拿起水桶，撲滅火焰。"
L["monstrous_summon"] = "殺死所有深淵先驅者以停止召喚。"
L["obsidian_extract"] = "摧毀所有虛空形成的黑曜石晶體。"
L["purging_flames"] = "撿起屍體，扔進火裡。"
L["pyre_amalgamated"] = "淨化材堆，然後殺死所有的小怪直到血肉融合體出現。"
L["ritual_ascension"] = "殺死日觸祭儀師。"
L["solar_collector"] = "在收集器的所有側面啟用所有五個單元。 單擊一個單元也會切換所有鄰近的單元。"
L["summoning_ritual"] = "殺死侍僧，然後關閉召喚傳送門。事件多次完成後，奈斐賽特周圍將產生一組三種稀有。"
L["titanus_egg"] = "消滅巨怪卵，然後擊敗精英怪年幼巨蟲，打不過就拉去旁邊階梯下讓NPC幫忙"
L["unearthed_keeper"] = "消滅出土的守衛者。"
L["virnall_front"] = "擊敗一波波的小怪，直到戰爭使者麥尼普塔出現。"
L["voidflame_ritual"] = "熄滅所有虛無之觸蠟燭。"

L["beacon_of_sun_king"] = "向內旋轉所有三個雕像。"
L["engine_of_ascen"] = "將所有四個雕像移入光束。"
L["lightblade_training"] = "殺死導師和新進者，直到『拂曉之刃』卡姆斯出生為止。"
L["raiding_fleet"] = "使用任務物品燃燒所有船隻。"
L["slave_camp"] = "打開附近的所有籠子。"
L["unsealed_tomb"] = "保護黑魯免遭怪物的襲擊。"

-------------------------------------------------------------------------------
------------------------------------ VALE -------------------------------------
-------------------------------------------------------------------------------

L["vale"] = "恆春谷"
L["vale_intro_note"] = "完成前置引導任務鏈，以解鎖恆春谷中的稀有物品，寶藏和攻擊任務。"

L["big_blossom_mine"] = "在繁花礦坑內，入口在東北。"
L["guolai"] = "在郭萊院中。"
L["guolai_left"] = "在郭萊院中 (左邊通道)。"
L["guolai_center"] = "在郭萊院中 (中央通道)。"
L["guolai_right"] = "在郭萊院中 (右邊通道)。"
L["pools_of_power"] = "在能量之池中，入口在黃金寶塔。"
L["right_eye"] = "放下全知之眼玩具的右半部分。"
L["tisiphon"] = "點擊丹妮爾的幸運釣竿。"

L["ambered_cache"] = "琥珀化寶箱"
L["ambered_coffer"] = "琥珀寶庫"
L["mantid_relic"] = "需要螳螂人聖物"
L["mogu_plunder"] = "魔古的財寶"
L["mogu_strongbox"] = "魔古寶箱"
L["mogu_relic"] = "需要魔古聖物"

L["abyssal_ritual"] = "殺死沉沒的擁護者然後殺死深淵巨怪。"
L["bound_guardian"] = "殺死三隻淵裔束縛者以釋放純淨水滴。"
L["colored_flames"] = "從火把上收集彩色火焰，並帶到相對應的符文上。"
L["construction_ritual"] = "將猛虎雕像推入光束中。"
L["consuming_maw"] = "淨化生長物和觸手，直到被踢出。"
L["corruption_tear"] = "點擊抓起一旁的巨大信標，在不讓旋轉的眼睛撞到你的情況下關閉裂口。"
L["electric_empower"] = "殺死參天呼換者，然後殺死『灌注者』馬奈可。"
L["empowered_demo"] = "關閉所有靈神聖匣"
L["empowered_wagon"] = "拿起影潘爆彈，將其放在戰車下方。"
L["feeding_grounds"] = "摧毀琥珀瓶和懸浮密室。"
L["font_corruption"] = "旋轉魔古雕像，直到兩個光束都到達後方，然後點擊控制台。"
L["goldbough_guardian"] = "保護族長金枝免受一波波怪物的襲擊。"
L["infested_statue"] = "將所有扭曲之眼從雕像上移開。"
L["kunchong_incubator"] = "摧毀所有力場產生器。"
L["mantid_hatch"] = "拿起影潘火焰噴射器並摧毀幼蟲孵化器。"
L["mending_monstro"] = "摧毀所有三個一組療癒琥珀。"
L["mystery_sacro"] = "摧毀所有可疑墓碑，殺死哀號之魂。"
L["noodle_cart"] = "在阿欽修裡拉麵推車時保護他。"
L["protect_stout"] = "保護洞穴免遭怪物的襲擊。"
L["pulse_mound"] = "殺死周圍的生物，然後殺死成長活體"
L["ravager_hive"] = "摧毀樹上所有的蜂巢。"
L["ritual_wakening"] = "殺死卡拉西喚醒者。"
L["serpent_binding"] = "殺死參天征服者，然後殺死昊風。"
L["stormchosen_arena"] = "清除競技場中的所有小怪，然後殺死氏族將軍。"
L["swarm_caller"] = "摧毀喚蟲者柱子。"
L["vault_of_souls"] = "打開金庫，摧毀所有雕像。"
L["void_conduit"] = "點擊虛空導管並擠壓觀察的眼睛。"
L["war_banner"] = "燃燒戰旗並殺死小怪，直到指揮官出現。"
L["weighted_artifact"] = "拿起古怪的重花瓶，穿越迷宮回到基座放置，中途如果被雕像打中花瓶會掉落。"

-------------------------------------------------------------------------------
----------------------------------- VISIONS -----------------------------------
-------------------------------------------------------------------------------

L["colored_potion"] = "彩色藥水"
L["colored_potion_note"] = [[
％s屍體旁邊的藥水始終指示運行的負面效果藥水的顏色。

+100理智藥水的顏色可以由該藥水的顏色確定（| cFFFF0000壞 | r => | cFF00FF00好 | r）：

黑色 => 綠色
藍色 => 紫色
綠色 => 紅色
紫色 => 黑色
紅色 => 藍色
]]

L["bear_spirit"] = "熊靈"
L["bear_spirit_note"] = "殺死憤怒的熊地毯靈和所有小怪，即可獲得10％的加速增益。"
L["buffs_change"] = "可用的增益每次都會更換。 如果建築物關閉或缺少NPC/物體，則本次該增益沒有提供。"
L["clear_sight"] = "需要清除視線等級 %d。"
L["craggle"] = "將玩具放在地面上（例如玩具火車組）以分散他的注意力。 拉開他的機器人，並先殺死他們。"
L["empowered"] = "賦能"
L["empowered_note"] = "穿過地雷的迷宮，站在樓上的實驗增益礦上，獲得10％的傷害增益。"
L["enriched"] = "充實"
L["enriched_note"] = "殺死被忽視的公會銀行，獲得10％暴擊增益。"
L["ethereal_essence"] = "超凡的精華"
L["ethereal_essence_note"] = "殺死Warpweaver Dushar，獲得10％暴擊增益。(暫譯)"
L["ethereal_note"] = "收集隱藏在整個幻象內的橙色晶體，並將其返回該NPC以獲取額外的獎勵。總計有10個水晶每個區域兩個。\n\n| cFF00FF00別忘了拾取箱子！|r"
L["heroes_bulwark"] = "英雄壁壘"
L["heroes_bulwark_note"] = "在旅館內殺死加蒙，獲得10％的生命增益。"
L["horrific_visions"] = "驚懼幻象"
L["inside_building"] = "在建築物內。"
L["mailbox"] = "郵箱"
L["mail_muncher"] = "開啟以後，郵件咀嚼者有機會出現。(暫譯)"
L["morgan_pestle"] = "Morgan Pestle"
L["odd_crystal"] = "奇怪的水晶"
L["requited_bulwark"] = "退役的壁壘"
L["requited_bulwark_note"] = "殺死Agustus Moulaine，可獲得7％的臨機應變增益。"
L["shave_kit"] = "髮捲的剃髮工具組"
L["shave_kit_note"] = "在理髮店裡面，拾取桌上的箱子。"
L["smiths_strength"] = "Smith's Strength"
L["smiths_strength_note"] = "在鐵匠小屋中殺死納羅斯，取得10％的傷害增益。"
L["spirit_of_wind"] = "風之精靈"
L["spirit_of_wind_note"] = "殺死布旺巴獲得10％的加速和移動速度提升。"
L["void_skull"] = "虛無之觸頭顱"
L["void_skull_note"] = "點擊地面上的頭顱以拾取玩具。"
L["yelmak"] = "Yelmak"

L["c_alley_corner"] = "在小巷的一個角落。"
L["c_bar_upper"] = "在酒吧的上層。"
L["c_behind_bank_counter"] = "在銀行櫃檯的後面。"
L["c_behind_boss"] = "在首領後方的流亡者建築。"
L["c_behind_boxes"] = "在一些盒子後面的角落。"
L["c_behind_cart"] = "在一輛被毀的推車後面。"
L["c_behind_house_counter"] = "在櫃檯後面的房子裡。"
L["c_behind_mailbox"] = "在郵箱後方。"
L["c_behind_pillar"] = "隱藏在使館大樓後方的支柱後面。"
L["c_behind_rexxar"] = "隱藏在雷克薩建築物後面的右側。"
L["c_behind_stables"] = "在肖爾的馬槽後。"
L["c_by_pillar_boxes"] = "在支柱和一些盒子之間的牆上。"
L["c_center_building"] = "在中心建築的底層。"
L["c_forge_corner"] = "在一個鍛造的角落。"
L["c_hidden_boxes"] = "隱藏在索爾建築後方的一些盒子後面。"
L["c_inside_auction"] = "在拍賣行內的右邊。"
L["c_inside_big_tent"] = "在大帳篷裡的左邊。"
L["c_inside_cacti"] = "在拐角處的仙人掌補丁裡。"
L["c_inside_hut"] = "在右邊的第一個小屋內。"
L["c_inside_leatherwork"] = "在製皮建築內。"
L["c_inside_orphanage"] = "在孤兒院裡。"
L["c_inside_transmog"] = "在塑形小屋內。"
L["c_left_cathedral"] = "隱藏在大教堂入口左側。"
L["c_left_inquisitor"] = "階梯左側的審訊官小首領的後面。"
L["c_on_small_hill"] = "在小山頂上。"
L["c_top_building"] = "在建築物的頂層。"
L["c_underneath_bridge"] = "在橋下。"
L["c_walkway_corner"] = "在角落的上層人行道上。"
L["c_walkway_platform"] = "在上走道上方的平台上。"

L["options_icons_visions_buffs"] = "增益"
L["options_icons_visions_buffs_desc"] = "顯示可以造成1小時傷害增強的事件的位置。"
L["options_icons_visions_chest"] = "寶箱"
L["options_icons_visions_chest_desc"] = "在驚懼幻象中顯示可能的寶箱位置。"
L["options_icons_visions_crystals"] = "奇怪的水晶"
L["options_icons_visions_crystals_desc"] = "在驚懼幻象中顯示奇怪的水晶位置。"
L["options_icons_visions_mail"] = "郵箱"
L["options_icons_visions_mail_desc"] = "顯示郵件咀嚼者坐騎的郵箱位置。"
L["options_icons_visions_misc"] = "其他"
L["options_icons_visions_misc_desc"] = "在驚懼幻象中顯示稀有、玩具、藥水和增強的位置。"

L["voldun"] = "沃魯敦"
L["elusive_alpaca"] = "餵羊駝濱海綜合綠色蔬菜以學習坐騎。 在一個位置出現10分鐘，然後很久才重生。"
L["options_icons_alpaca_voldun_desc"] = "顯示玄渺快蹄出現的位置。"
L["options_icons_alpaca_voldun"] = "玄渺快蹄"
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
---------------------------------- COVENANTS ----------------------------------
-------------------------------------------------------------------------------

L["covenant_required"] = "需要 %s 誓盟成員。"
L["anima_channeled"] = "靈魄連接到 %s"

-------------------------------------------------------------------------------
--------------------------------- ARDENWEALD ----------------------------------
-------------------------------------------------------------------------------

L["deifir_note"] = "騎上圈內的稀有並使用 {spell:319566} 和 {spell:319575} 使其減速和昏迷。"
L["faeflayer_note"] = "瀑布後面隱藏的小洞穴內。"
L["gormtamer_tizo_note"] = "在霧紗密林擊殺豎果妖精直到 {npc:164110} 刷新。"
L["humongozz_note"] = "種植一個 {item:175247} 到潮濕的沃土後將刷新 {npc:164122}。區域內的許多怪物都會掉落蘑菇。"
L["lehgo_note"] = "摧毀顫動的果姆蛋並擊殺 {npc:171827} 直到他出現。在洞穴內（入口在東南黃塵地穴內）"
L["macabre_note"] = [[
有多個刷新點。要召喚稀有，含另外兩個其他玩家戰在神秘的蘑菇環上並且對彼此跳舞。

• 玩家1對玩家2跳舞
• 玩家2對玩家3跳舞
• 玩家3對玩家1跳舞
]]
L["mymaen_note"] = "擊殺區域內的腐棘精靈直到他做出表情並出現。"
L["rainbowhorn_note"] = [[
找到並點擊|cffffff00符文雄鹿巨角|r來召喚稀有，角會在亞登曠野多個地點刷新。

他總是在特那瓦勒北邊刷新，所以設定你的 {item:6948} 到那裏並注意附近區域的表情。

|cffff5400品|r|cffffaa00嘗|r|cffffff00絕|r|cffaaff00妙|r|cff54ff00的|r |cff00ff55美|r|cff00ffa9麗|r|cff00ffff的|r |cff0055ff七|r|cff0000ff彩|r|cff5400ff之|r|cffaa00ff虹|r|cffff00ff好|r|cffff00aa味|r|cffff0054道|r|cffff0000！|r
]]
L["rootwrithe_note"] = "觸碰 {npc:167928} 直到稀有出現。"
L["rotbriar_note"] = "和 {npc:171684} 交談對話後在附近召喚稀有。"
L["slumbering_note"] = "跑到迷霧中將會昏迷並被帶出。使用信號彈或有範圍法術的寵物將他擊出迷霧。"
L["skuld_vit_note"] = "在被障礙物阻擋的山洞中。暗夜妖精必須使用 {spell:310143} 進入洞穴。他進入戰鬥後，障礙物將消失。"
L["valfir_note"] = "在閃亮的靈魄種子下降過程中點選並使用 {spell:338045} 移除他的 {spell:338038} 增益。"
L["wrigglemortis_note"] = "拉動 {npc:164179} 刷新稀有。"

L["night_mare_note"] = [[
前往特那希，並沿著西北懸崖的樹根路前往破損的車。在那的地面上可以拾取 {item:181243}。

把此物品帶給位於爍瀑高地的 {npc:165704}。她將給你一個 {item:181242} 換成10個 {item:173204}。|cFFFF8C00如果她不在這裡，你必須完成|cFFFFFD00小果姆飼育區的麻煩|r和|cFFFFFD00狡詐的木魈|r任務線。|r

接下來，和森林之心的 {npc:160262} 交談兌換 {item:181242} 為 {item:178675}。使用此物品得到 {spell:327083} 增益，可以讓你看見 {npc:168135}。
]]

L["star_lake"] = "星湖劇場"
L["star_lake_note"] = [[
與舞臺導演 {npc:171743} 交談，會開啟一場特殊的戰鬥。 戰鬥每天會變更。

參加所有7個戰鬥會從 {npc:163714} 解鎖 {item:180748}。
]]
L["guldan"] = "古爾丹"

L["cache_of_the_moon"] = "在黑夜花園收集 {npc:171360} 的五個遺失工具並組合它們以製造 {item:180753}。交給她工具包後會施放 {spell:334353} 給你，讓你可以看到寶箱"
L["cache_of_the_night"] = "在整個區域收集 {item:180656}、{item:180654} 和 {item:180655} 組合它們製造 {item:180652}。"
L["darkreach_supplies"] = "跳上 {npc:169995} 並滑翔到西南方進入空心山峰到達暗夜妖精寶藏上面。"
L["desiccated_moth"] = "在標註位置拾取 {item:180784} 後，在樹的西北方跳上 {npc:169997} 來滑翔到樹梢上，在薰香爐使用後。點選 {npc:171484} 來取得寵物。"
L["dreamsong_heart"] = "使用 {npc:169997} 滑翔到東北方的樹上。"
L["elusive_faerie_cache"] = "拾取 {spell:333923} 在日暮林地的東北角並使用拾取寶箱。"
L["enchanted_dreamcatcher"] = "懸掛在樹根頂上。從西側往上跳最容易。"
L["faerie_trove"] = "位於平臺下方"
L["harmonic_chest"] = "需要兩名玩家。一名玩家彈琴另一名玩家擊鼓來解鎖寶箱。"
L["hearty_dragon_plume"] = "在附近瀑布的頂部點選 {spell:333554}，然後用它向下漂浮到樹枝上。"
L["old_ardeite_note"] = "在爍枝東南方擊殺 {npc:160747} 和 {npc:160748} 得到 {item:174042}。使用此物品飛到附近稀有上面並標記它。"
L["swollen_anima_seed"] = "在樹幹裡面的一顆大種子"

L["playful_vulpin_note"] = [[
在 {npc:171206} 找到並使用正確的表情五次後獲得寵物。

• 開始好奇的挖掘 = |cFFFF8C00/curious（/好奇）|r
• 仍然徘徊在無法坐下的地方 = |cFFFF8C00/sit（/坐下）|r
• 獨自一人唱歌 = |cFFFF8C00/sing（/唱歌）|r
• 歡樂地跳舞 = |cFFFF8C00/dance（/跳舞）|r
• 孤獨悲傷的坐著 = |cFFFF8C00/pet（/拍）|r
]]

L["tame_gladerunner"] = "馴服的巡林者"
L["tame_gladerunner_note"] = [[
閱讀樹上的 “密林傳奇” 並跟隨藍色的燈穿過小徑到達 {npc:171767}。擊殺他並拾取 {npc:171699}。

如果你走錯路而且當你到終點時 {npc:171699} 已經消失了，返回開始的位置並再次閱讀 “密林傳奇” 來再次嘗試。如果 {npc:171767} 不在，你需要在此等待他刷新。
]]

L["faryl_note"] = "讓天空中的生物來帶領亞登曠野的守軍吧。"
L["glitterdust_note"] = "亞登曠野的生物或許看起來很溫馴，不過為了守護家園，他們願意拿出無與倫比的力量和勇氣。你也有這種覺悟嗎？"

L["lost_book_note"] = "把這本遺失的書交回給在記憶林地的 {npc:165867}"
L["options_icons_faerie_tales"] = "{achievement:14788}"
L["options_icons_faerie_tales_desc"] = "顯示 {achievement:14788} 成就中遺失的書的位置"

-------------------------------------------------------------------------------
----------------------------------- BASTION -----------------------------------
-------------------------------------------------------------------------------

L["aegeon_note"] = "在附近區域殺死敵人直到執法者艾吉昂作為增援刷新"
L["ascended_council_note"] = "與其他四名玩家，同時點擊五個神廟的暮鐘召喚志士試煉場的 {npc:170899}。"
L["aspirant_eolis_note"] = "拾取附近的 {item:180613} 並將該 NPC 設為目標後閱讀來啟動他。"
L["baedos_note"] = "從周圍地區帶一盤發酵的普恩果給 {npc:161536} 直到她啟動。"
L["basilofos_note"] = "在岩石上移動，直到紫色的追蹤標記出現在你的頭頂。 站著不動，等待四種表情出現，然後他會刷新"
L["beasts_of_bastion"] = "昇靈堡的野獸"
L["beasts_of_bastion_note"] = "和 {npc:161441} 交談召喚四個野獸中的一個。"
L["bookkeeper_mnemis_note"] = "在此區有機率代替 {npc:166867} 單位刷新"
L["cloudfeather_patriarch_note"] = "在此區擊殺 {npc:158110} 直到稀有做出表情和刷新"
L["collector_astor_note"] = "閱讀散落在房間裡的全部共六章的瑪西雅的傳承，之後和 {npc:157979} 交談會得到 {spell:333779}，讓你在西北方找到隱藏的 {item:180569}。交還章節將刷新稀有"
L["corrupted_clawguard_note"] = "在房間或是在煉火哨站山上拾取 {item:180651} 並使用它修理 {npc:171300}"
L["dark_watcher_note"] = "只在死亡後可以看到。和她交談會在攻擊之前對你施放 {spell:332830} "
L["demi_hoarder_note"] = "剛開始時會有99層的 {spell:333874}，降低所承受的傷害。受到傷害後堆疊緩慢消失。稀有將沿著固定路徑移動，如果到達路徑終點則會消失"
L["dionae_note"] = "當她變為免疫時，點選四個 {npc:163747} 來打破她的護盾"
L["herculon_note"] = [[
收集 {item:172451} 並使用來對 {npc:158659} 堆疊 {spell:343531}。堆到10層時，他會啟動

可以從房間內或室外的耗盡的靈魄之罐中收集微粒。

|cFFFF8C00不能在世界任務 {wq:進攻門廊} 期間擊敗。|r
]]
L["nikara_note"] = "和兩名其他玩家，點選遠古焚香來召喚。"
L["sotiros_orstus_note"] = "點選黑色的鐘召喚稀有。"
L["sundancer_note"] = "點選雕像獲得 {spell:332309} 增益，然後使用 {item:180445} 滑翔到稀有並騎上它。"
L["swelling_tear_note"] = "點選 {npc:171012} 召喚三個稀有中的一個。眼淚可以在區域內的多個位置出現。"
L["unstable_memory_note"] = "當 {npc:171018} 存在時可以刷新。拉一個 {npc:171018} 到其它會給它10層堆疊 {spell:333558}，把它變成稀有。"
L["wingflayer_note"] = "點擊附近桌上的勇氣號角召喚（東南方，樓梯上）。"

L["broken_flute"] = "擊殺附近的 {npc:170009} 直到掉落 {item:180536}，使用此工具修理它。"
L["cloudwalkers_coffer"] = "雲行者寶箱"
L["cloudwalkers_coffer_note"] = "使用大型紫色花來彈跳到平台上。"
L["experimental_construct_part"] = "拾取附近 {item:180534} 並使用修理部件。靈魄有多個刷新地點。"
L["larion_harness"] = "位於野獸大廳內。"
L["memorial_offering"] = "在昇靈堡多個位置之一找到 {npc:171526} 並購買 {item:180788}。將其放在靠近寶箱的飲料托盤中以獲取 {item:180797}。"
L["scroll_of_aeons"] = "在中心地區拾取2個 {item:173973} 並將它們放在附近的貢品盤上顯出寶藏。"
L["vesper_of_silver_wind"] = "銀風禱鐘"
L["vesper_of_silver_wind_note"] = "完成 {achievement:14339} 成就並和晉升之巔入口的 {npc:171732} 交談鑄造 {item:180858}。"

L["gift_of_agthia"] = "點擊通往西北方斷橋的火炬並攜帶 {spell:333320} 從火炬到火炬直到到達寶箱。點亮最後的火炬你會受益 {spell:333063}。"
L["gift_of_chyrus"] = "在寶箱前面跪下將被授予 {spell:333045}。"
L["gift_of_devos"] = [[
寶箱西南方一個火炬可以拾取獲得 {spell:333912}。上坐騎，進入戰鬥或受到傷害時火焰會掉落。必須找到回到寶箱的路並將火焰放在虔誠的火盆以獲取 {spell:333070}。

拾取火焰之前，清除寶箱前面的全部怪物。在運送火焰時，點擊任意路上的 {npc:156571} 獲得 {spell:335012} 負面效果提高移動速度。
]]
L["gift_of_thenios"] = [[
在寶箱後面有稱為“智慧之路”的飛行平台。它通往了一系列有著可以進行溝通的不同薰香的平台：

• 知識薰香
• 耐心薰香
• 洞察薰香
• 審判薰香

按照 耐心 => 知識 => 洞察 的順序來溝通。最後在審判平臺“審判之路”的寶珠將會出現。

這個寶珠將把你進入真正的審判薰香。與它溝通後最後的飛行平臺會讓你獲得 {spell:333068} 來打開寶箱。
]]
L["gift_of_vesiphone"] = "敲鐘刷新一個 {npc:170849} 並擊殺獲得 {spell:333239} 負面效果。寶箱正對面的流水將清潔此負面效果，並獲得 {spell:332785}。"

L["count_your_blessings_note"] = "放置一個 {item:178915} 在貢碗內獲得祝福。"
L["options_icons_blessings"] = "{achievement:14767}"
L["options_icons_blessings_desc"] = "顯示 {achievement:14767} 成就中貢碗的位置。"

L["vesper_of_courage"] = "勇氣暮鐘"
L["vesper_of_humility"] = "謙遜暮鐘"
L["vesper_of_loyalty"] = "忠誠暮鐘"
L["vesper_of_purity"] = "純潔暮鐘"
L["vesper_of_wisdom"] = "智慧暮鐘"
L["vespers_ascended_note"] = "與其它四個暮鐘同時點擊此暮鐘召喚志士試煉場的 {npc:170899}。"
L["options_icons_vespers"] = "{achievement:14734}"
L["options_icons_vespers_desc"] = "顯示 {achievement:14734} 成就中暮鐘的位置。"

L["anima_shard"] = "失落的靈魄碎片"
L["anima_shard_61225"] = "在橋下的較低平臺上。"
L["anima_shard_61235"] = "在瀑布上方的壁架上。"
L["anima_shard_61236"] = "在主體結構中間的拱頂上。"
L["anima_shard_61237"] = "在水面上方的壁架上。"
L["anima_shard_61238"] = "在水中的一座小橋下。"
L["anima_shard_61239"] = "在薄石柱上。"
L["anima_shard_61241"] = "在初思之廳入口上方。"
L["anima_shard_61244"] = "在懸崖邊的一塊岩石上。"
L["anima_shard_61245"] = "在小瀑布上方的岩石上。"
L["anima_shard_61247"] = "在牆上的小水具上方。"
L["anima_shard_61249"] = "隱藏在純潔之巔上層的石柱後面。"
L["anima_shard_61250"] = "位在樓梯後面。"
L["anima_shard_61251"] = "位在小鈴鐺下面。"
L["anima_shard_61253"] = "在一個下落的石拱道頂部。"
L["anima_shard_61254"] = "在一個小的木結構上。"
L["anima_shard_61257"] = "在 {npc:162523} 正下方的小壁架上。"
L["anima_shard_61258"] = "在英雄之陵下面的小壁架上。"
L["anima_shard_61260"] = "在平臺下的地面上。"
L["anima_shard_61261"] = "在 {npc:163460} 洞穴上面的壁架上。"
L["anima_shard_61263"] = "在石柱上。"
L["anima_shard_61264"] = "在傾斜結構的頂部。"
L["anima_shard_61270"] = "位在樹的底部。"
L["anima_shard_61271"] = "在上層平臺的一個書櫃中。"
L["anima_shard_61273"] = "在突出懸崖正下方的壁架上。"
L["anima_shard_61274"] = "隱藏在平臺下方。"
L["anima_shard_61275"] = "在野獸大廳一些桶的後面。"
L["anima_shard_61277"] = "在薄石柱上。"
L["anima_shard_61278"] = "在岩石下的橋下。"
L["anima_shard_61279"] = "在薄石柱上。"
L["anima_shard_61280"] = "在桌子的一角。"
L["anima_shard_61281"] = "在紀念祭珍品上方的壁架上。"
L["anima_shard_61282"] = "在懸崖頂下的壁架上。 跳到旁邊的岩石上，否則您將被傳送回去。"
L["anima_shard_61283"] = "彌莉的禮拜堂下面洞穴內，在桶後面。"
L["anima_shard_61284"] = "在岩石懸突下的壁架上，向南行。"
L["anima_shard_61285"] = "在一個小的岩石壁架的盡頭。"
L["anima_shard_61286"] = "在俯瞰道路的壁架上。"
L["anima_shard_61287"] = "在小瀑布上方的壁架上。"
L["anima_shard_61288"] = "在小壁架的頂端。"
L["anima_shard_61289"] = "在涼亭上。"
L["anima_shard_61290"] = "在狹窄的岩石壁架的盡頭。"
L["anima_shard_61291"] = "在的池塘底部雕像腳下。"
L["anima_shard_61292"] = "在石牌坊的頂部。"
L["anima_shard_61293"] = "在較低水準的細石柱上。"
L["anima_shard_61294"] = "隱藏在一堆桶後面。"
L["anima_shard_61295"] = "在書架上 {npc:156889} 後面。"
L["anima_shard_61296"] = "在倒下的大鐘後面。\n\n死靈戰地副本內。"
L["anima_shard_61297"] = "在石柱後面。\n\n死靈戰地副本內。"
L["anima_shard_61298"] = "位在躺椅後面。"
L["anima_shard_61299"] = "隱藏在大火炬的後面。"
L["anima_shard_61300"] = "掛在中央字體的壁架上。"
L["anima_shard_spires"] = nil
L["options_icons_anima_shard"] = "{achievement:14339}"
L["options_icons_anima_shard_desc"] = "顯示 {achievement:14339} 成就中全部50個失落的靈魄碎片的位置。"

L["stratios_note"] = "就算是規模再小的戰爭，也要慎重以對。等你準備好了，就展示你的隊伍。"
L["thenia_note"] = "這裡有如此廣大的開放平原。正好適合拿來戰鬥。你準備好了嗎？"
L["zolla_note"] = "我們非常嚴肅看待我們的防禦。無論大小，我們都致力於善用每一分資源，保護昇靈堡。"

-------------------------------------------------------------------------------
--------------------------------- MALDRAXXUS ----------------------------------
-------------------------------------------------------------------------------

L["chelicerae_note"] = "摧毀 {npc:159885} 後啟動稀有。"
L["deepscar_note"] = "可能出現在苦痛劇場的多個入口。"
L["forgotten_mementos"] = "在寶藏西側的房間拖拽寶庫閘門之鏈打開大門。"
L["gieger_note"] = "攻擊 {npc:162815} 後啟動稀有。"
L["gristlebeak_note"] = "破壞附近的 {npc:162761} 後啟動稀有。"
L["leeda_note"] = "擊殺兩個 {npc:162220} 單位後稀有刷新。"
L["nirvaska_note"] = "只在世界任務 {wq:死亡宣告} 存在時啟動"
L["sabriel_note"] = "可以作為苦痛劇場的冠軍之一出現。"
L["schmitd_note"] = "使用附近的 {spell:313451} 破壞他的護盾。"
L["taskmaster_xox_note"] = "與 {npc:160204}，{npc:160230} 和 {npc:160226} 共享刷新。"
L["theater_of_pain_note"] = "你每天第一次殺死首領都會有機會掉落坐騎。"
L["zargox_the_reborn_note"] = [[
使用 {item:175841} 位於 {npc:157124} 頂上。獲得寶珠，你必須完成 {npc:157076} 的任務 {quest:57245} 之後再與他交談。"

假如 {npc:157124} 不起來，復活區域內的 {npc:157132} 直到他出現。
]]
L["mixed_pool_note"] = [[
從周圍怪物收集材料並扔進池中。每30個材料，根據所使用的組合，將刷新七個稀有中的一個。

• 從北側的 {npc:167923} 和 {npc:167948} 收集 {spell:306713}。

• 從南側的 {npc:165015} 和 {npc:171142} 收集 {spell:306719}。

• 從南側的 {npc:165027} 和 {npc:166438} 收集 {spell:306722}。

殺死每個稀有一次來取得 {item:183903} 玩具。
]]

L["blackhound_cache"] = "黑犬儲物箱"
L["blackhound_cache_note"] = "在憎惡體工廠召喚 {npc:157843}，然後護送他到黑犬崗哨。"
L["bladesworn_supply_cache"] = "刃誓補給箱"
L["cache_of_eyes"] = "蛛眼寶箱"
L["cache_of_eyes_note"] = "在盲目要塞有多個刷新點。"

L["glutharns_note"] = "在軟泥瀑布後面的一個山洞裡。擊殺 {npc:172485} 和 {npc:172479} 解鎖寶箱。"
L["kyrian_keepsake_note"] = "檢查 {npc:169664} 拾取寶藏。"
L["misplaced_supplies"] = "在巨大的蘑菇頂上。跑上山後跳上較小的棕色蘑菇，再跑到較大的山丘後跳上巨大的蘑菇。"
L["necro_tome_note"] = "要進入塔樓，必須完成一個 {npc:166657} 的小任務線。在頂層的書櫃裡。"
L["plaguefallen_chest_note"] = [[
站在綠色軟泥中（需要治療！）獲得10層 {spell:330069} 並會轉化為 {spell:330092}。

轉化後，到 {npc:158406} 平台（入口在東側）下面洞穴並點擊管線來傳送到寶箱。
]]
L["ritualists_cache_note"] = "從骨頭堆（多個刷新點）拾取 {item:181558}。在 {npc:174386} 後面使用它完成裝訂儀式書並獲得 {spell:337041} 增益。"
L["runespeakers_trove_note"] = "東側找到 {npc:170563} 並擊殺他獲得 {item:181777}。"
L["stolen_jar_note"] = "在巨大的蘑菇下面的山洞裡。"
L["strange_growth_note"] = "攻擊 {npc:165037} 獲得寶藏。"
L["vat_of_slime_note"] = "點擊桌上的瓶子，然後點擊軟泥桶。"

L["giant_cache_of_epic_treasure"] = "巨大的史詩寶箱"
L["spinebug_note"] = [[
快看！{spell:343124}！勇敢的冒險家快過去，這肯定不是詭計。等一下，那是卡拉贊的音樂嗎？{npc:174663} 在這裡幹嘛…？

{spell:343163}!
]]

L["oonar_sorrowbane_note"] = [[
在苦痛劇場，可以找到哀禍插在地上和烏納的手臂附在一起。|cFFFF8C00在嘗試拉出之前，設置 {item:6948} 到 {npc:161702} 飛行點。|r

拉出 {item:181164}：

• 到格魯薩恩凋亡地東側。
• 吃4層 {spell:327367} （2分鐘負面效果）。
• 迅速爐石並拉動手臂。

拉出 {item:180273}：

• 從瑞文崔斯的 {npc:171808} 買個 {item:182163}。
• 從瑪卓薩斯的 {npc:166640} 買個 {item:180771}。
• 從 |cFFFFFD00{wq:顛跛之路}|r 世界任務西側得到2層 {spell:306272}。
• 在格魯薩恩凋亡地吃4層 {spell:327367}。
• 迅速爐石，喝下2種藥水並拉出大寶劍。
]]

L["pet_cat"] = "寵愛該死的貓！"
L["hairball"] = "只在瘟疫之臨副本內的膿瘡聖所出現！"
L["lime"] = "位在大骨頭拱頂上。"
L["moldstopheles"] = "繞到莖稈後面並跳上蘑菇平臺。到達最後的平臺，使用坐騎並在莖稈上跳來跳去到達。"
L["pus_in_boots"] = "在橋的下面。"

L["options_icons_slime_cat"] = "{achievement:14634}"
L["options_icons_slime_cat_desc"] = "顯示 {achievement:14634} 成就中貓咪的位置。"

L["dundley_note"] = "我會一路過關斬將，直到獲得我應得的尊敬！唯一的壞處是我的個人物品都變得黏黏的，無一倖免。"
L["maximillian_note"] = "我等了這麼多年，就是想要一個好對手。贏家擁有所有戰利品！"
L["rotgut_note"] = "腐腸、殘渣。多出來的。你要打。"

-------------------------------------------------------------------------------
--------------------------------- REVENDRETH ----------------------------------
-------------------------------------------------------------------------------

L["amalgamation_of_filth_note"] = "當世界任務 {wq:苦差事：拆除小隊} 可做時點選一個垃圾箱並使用 {spell:324115} 進入水裡。"
L["amalgamation_of_light_note"] = "移動全部三個鏡子陷阱釋放稀有。"
L["amalgamation_of_sin_note"] = "在世界任務 {wq:召喚你的罪孽} 的期間拾取能量催化劑有機會獲得 {item:180376} 並使用它來召喚稀有。"
L["bog_beast_note"] = "世界任務 {wq:越髒越好} 期間有機率刷新後給 {npc:166206} 使用 {item:177880}。"
L["endlurker_note"] = "在微光裂隙頂上點選 {npc:165229} 屍體附近的靈魄之樁並使用 {spell:321826}。"
L["executioner_aatron_note"] = "擊殺三個附近的 {npc:166715} 移除 {spell:324872}。"
L["famu_note"] = "和 {npc:166483} 交談觸發事件。"
L["grand_arcanist_dimitri_note"] = "擊殺四個 {npc:167467} 釋放稀有。"
L["harika_note"] = "在掘息坑西側，拾取 {item:176397}，然後把箭交給 {npc:165327} 後和他交談擊落稀有。"
L["innervus_note"] = "擊殺附近的 {npc:160375} 獲得 {item:177223} 並打開墓穴。"
L["leeched_soul_note"] = "進入附近的墓穴。走到 {npc:165151} 附近開始事件。"
L["lord_mortegore_note"] = "擊殺周圍的怪物獲得 {item:174378} 並使用它強化 {npc:161870}。所有四個徽記獲得強化，稀有就會刷新。"
L["madalav_note"] = "點選鐵砧附近的馬達拉夫的錘子召喚他。"
L["manifestation_of_wrath_note"] = "當世界任務 {wq:群聚靈魂} 的 {npc:169916} 恢復後有幾率刷新稀有。"
L["scrivener_lenua_note"] = "返還禁忌圖書館 {npc:160753}。"
L["sinstone_hoarder_note"] = "嘗試拾取 {npc:162503} 後稀有會出來。"
L["sire_ladinas_note"] = "拾取附近的聖光餘暉並對 {npc:157733} 使用 {spell:313065}"
L["soulstalker_doina_note"] = "當她逃跑時跟隨下樓並穿過鏡子。"
L["tomb_burster_note"] = "當 {npc:155777} 被網困住時會刷新。擊殺附近 {npc:155769} 和幾波 {npc:155795} 直到稀有刷新。"
L["worldedge_gorger_note"] = [[
擊殺禍孽森林和歿路沼澤的{npc:160815}、{npc:163960}和{npc:163961}等類似怪物來獲得一個 {item:173939}。使用它點燃世界邊緣火盆來召喚稀有。

有幾率會掉落一個 {item:180583}，可以開啟七天任務線來獲得 {spell:333027} 坐騎。
]]

L["dredglaive_note"] = "在 {npc:173671} 屍體的橋下。"
L["forbidden_chamber_note"] = "在鎖著的門前拾取一個廢棄的靈魄之罐並學習 {spell:340701}。使用它吸取五個附近的 {npc:173838s}，然後在 {npc:173786} 前使用 {spell:340866}。"
L["gilded_plum_chest_note"] = "擊殺在路上徘徊的 {npc:166680}。"
L["lost_quill_note"] = "從禁忌圖書館的桌上瓶子拾取 {item:182475}，然後把它交給外面拱門頂上的 {npc:173449}。"
L["rapier_fearless_note"] = "點擊地上的劍杆，然後擊敗 {npc:173603}。"
L["remlates_cache_note"] = "在暗隱村墓穴後面的外牆上。"
L["smuggled_cache_note"] = "*在拾取之前*：請確認已完成 {quest:60480} 支線任務否則寶藏和任務將缺少40個 {currency:1820}。"
L["taskmaster_trove_note"] = '閱讀"出入口儀式"然後小心地閃過球走到寶箱。'
L["the_count_note"] = "在歿路沼澤農99個 {currency:1820} 然後把它帶給 {npc:173488}。"

L["forgotten_anglers_rod"] = "被遺忘的漁翁之竿"

L["loyal_gorger_note"] = "到歿路沼澤完成 {npc:173498} 的每日任務七次將以坐騎獲得他。"

L["sinrunner_note"] = "將食物和補給品帶給 {npc:173468} 持續六天後可獲得她的韁繩。她一次只會出現幾分鐘。"
L["sinrunner_note_day1"] = "在西部荒野農場撿8個 {item:182581} 給布蘭契。"
L["sinrunner_note_day2"] = "從暗隱村的 {npc:173570} 獲得 {item:182585} 並梳理布蘭契。"
L["sinrunner_note_day3"] = "在暗隱村道路周圍找到4個 {item:182595} 給布蘭契裝配上。"
L["sinrunner_note_day4"] = "在 {npc:173570} 附近拾取 {item:182620} 並用昇靈堡或亞登曠野的水把它裝滿。把 {item:182599} 給布蘭契。"
L["sinrunner_note_day5"] = "從深夜市集的 {npc:171808} 用不同的肉換取 {item:182597}，給布蘭契裝上。"
L["sinrunner_note_day6"] = "從城牆破洞的 {npc:167815} 購買3個 {item:179271}，餵食布蘭契。"

L["options_icons_carriages"] = "馬車"
L["options_icons_carriages_desc"] = "顯示可騎乘馬車的位置和路徑。"
L["options_icons_dredbats"] = "{npc:161015}"
L["options_icons_dredbats_desc"] = "顯示{npc:161015}的位置和路徑。"
L["options_icons_sinrunners"] = "{npc:174032}"
L["options_icons_sinrunners_desc"] = "顯示{npc:174032}的位置和路徑。"

L["addius_note"] = "意志軟弱的傢伙不該浪費我的時間，不過，要是你堅持的話，我會讓你見識真正的痛苦。"
L["eyegor_note"] = "埃格準備好戰鬥了！"
L["sylla_note"] = "誰也想不到居然能在這種糟糕的地方展開這麼特別的戰鬥，但人算不如天算。不要浪費我的時間。"

L["avowed_ritualist_note"] = "帶附近的 {npc:160149} 到這裡來赦免他們"
L["fugitive_soul_note"] = "帶 {npc:160149} 到附近的 {npc:166150} 來開始赦免儀式"
L["souls_absolved"] = "靈魂被赦免"
L["options_icons_fugitives"] = "{achievement:14274}"
L["options_icons_fugitives_desc"] = "顯示 {achievement:14274} 成就中赦免靈魂的位置"

L["grand_inquisitor_note"] = "把10個 {item:180451} 交給 {npc:160248} 有機會獲得此罪孽石。"
L["high_inquisitor_note"] = "把250個 {currency:1816} 交給 {npc:160248} 有機會獲得此罪孽石。"
L["inquisitor_note"] = "把100個 {currency:1816} 交給 {npc:160248} 有機會獲得此罪孽石。"
L["options_icons_inquisitors"] = "{achievement:14276}"
L["options_icons_inquisitors_desc"] = "顯示 {achievement:14276} 成就中審判官的位置。"

-------------------------------------------------------------------------------
----------------------------------- THE MAW -----------------------------------
-------------------------------------------------------------------------------

L["return_to_the_maw"] = "重返淵喉"
L["maw_intro_note"] = "從 {npc:162804} 開始指引任務線以解鎖淵喉的稀有和事件。"

L["apholeias_note"] = "和3名其他玩家，站在平臺的角落並施放 {spell:331783} 召喚稀有。"
L["dekaris_note"] = "在一個大型的突出岩石上。"
L["drifting_sorrow_note"] = "在懸浮寶珠附近殺死 {npc:175246} 來啟動首領。"
L["ekphoras_note"] = "和3名其他玩家，站在平臺的角落並施放 {spell:330650} 召喚稀有。"
L["gorged_shadehound_note"] = "只在 {wq:狩獵：暗影獵犬} 事件期間可用"
L["ikras_note"] = "環繞墮滅堡飛行。這是個攻擊他的好位置。"
L["orophea_note"] = "從東南方的拾取 {spell:337143} 並提供給 {npc:172577} 啟動。"
L["sanngror_note"] = "如果他是無法攻擊的，等到她停止對靈魂做實驗即可。"
L["talaporas_note"] = "和3名其他玩家，站在平台的角落並施放 {spell:331800} 召喚稀有。"
L["valis_note"] = "按正確順序點擊三個 {npc:174810} 召喚稀有。順序每次點擊都會更換並且錯誤點擊符文會受到傷害和負面效果 {spell:343636}。"
L["yero_note"] = "靠近 {npc:172862} 然後跟著他進入附近的一個山洞，在那裡他變為敵對。"

L["exos_note"] = [[
擊殺其他三個悲傷、痛苦和失落先驅收集他們的銘刻。

• {item:182328}
• {item:182326}
• {item:182327}

組合全部三個刻印製造 {item:182329}，可以用來在統禦祭壇召喚稀有。使用 {npc:173892} 到達上層。
]]

L["soul_well_note"] = "接住從靈魂之井爆發出來的冥魄。"
L["obliterated_soul_shards_note"] = "在橋上收集 {item:177834}。"

L["animaflow_teleporter_note"] = "啟動即可直接旅行到淵喉的其他位置"
L["chaotic_riftstone_note"] ="啟動 {spell:344157} 來快速穿越淵喉。"
L["venari_note"] = [[
使用 {currency:1767} 購買淵喉和托迦司升級。

|cFFFF8C00在分身上，帳號通用的托迦司升級將顯示未完成|r
|cFFFF8C00解鎖後，下面的完成狀態將更新！|r
]]
L["venari_upgrade"] = "{npc:162804} 升級"
L["torghast"] = "托迦司"
L["Ambivalent"] = "籠統"
L["Appreciative"] = "感謝"
L["Apprehensive"] = "不安"
L["Cordial"] = "友善"
L["Tentative"] = "猶豫"

L["stygian_cache"] = "冥魄聖匣"
L["stygian_cache_note"] = "每次重生只有一個人能夠拾取"

L["box_of_torments_note"] = "在悲慘之牢下方開啟 {npc:173837}"
L["tormentors_notes_note"] = "拾取 {npc:173811} 的屍體"
L["words_of_warden_note"] = "在一些罐子後面的石頭上檢查 {npc:173841}"

L["options_icons_bonus_boss"] = "獎勵精英"
L["options_icons_bonus_boss_desc"] = "顯示獎勵精英位置。"
L["options_icons_bonus_event"] = "獎勵事件"
L["options_icons_bonus_event_desc"] = "顯示獎勵事件位置。"
L["options_icons_riftstone"] = "{npc:174962}"
L["options_icons_riftstone_desc"] = "顯示混亂裂隙石傳送者位置。"
L["options_icons_grapples"] = "{npc:176308}"
L["options_icons_grapples_desc"] = "顯示使用 {item:184653} 升級後可使用的 {npc:176308} 位置"
L["options_icons_maw_lore"] = "淵喉知識物品"
L["options_icons_maw_lore_desc"] = "顯示 {achievement:14761} 成就中淵喉知識物品的位置"
L["options_icons_stygian_caches"] = "冥魄儲藏箱"
L["options_icons_stygian_caches_desc"] = "顯示含有額外冥魄寶箱的位置"

-------------------------------------------------------------------------------
----------------------------------- ICECROWN ----------------------------------
-------------------------------------------------------------------------------

L["prepatch_intro"] = "完成暗影之境前夕事件前置任務來解鎖此區域的首領"
L["icecrown_rares"] = "所有首領以固定順序每10分鐘刷新一個.每個首領一天可以拾取多次"
L["next_spawn"] = "下次刷新時間為本地時間 %s "

local ORIG = "原本位於 %s。"

L["orig_atk"] = ORIG:format(EJ_GetInstanceInfo(271))
L["orig_azn"] = ORIG:format(EJ_GetInstanceInfo(272))
L["orig_dtk"] = ORIG:format(EJ_GetInstanceInfo(273))
L["orig_fos"] = ORIG:format(EJ_GetInstanceInfo(280))
L["orig_hor"] = ORIG:format(EJ_GetInstanceInfo(276))
L["orig_icc"] = ORIG:format(EJ_GetInstanceInfo(758))
L["orig_nax"] = ORIG:format(EJ_GetInstanceInfo(754))
L["orig_pos"] = ORIG:format(EJ_GetInstanceInfo(278))
L["orig_tot"] = ORIG:format(EJ_GetInstanceInfo(284))
L["orig_utk"] = ORIG:format(EJ_GetInstanceInfo(285))
L["orig_utp"] = ORIG:format(EJ_GetInstanceInfo(286))
----------------------------------- VOLDUN ------------------------------------
L["voldun"] = "Vol'dun"
L["elusive_alpaca"] = "Feed the alpaca Seaside Leafy Greens Mix to learn it as a mount. Appears for 10 minutes in one location, then a long respawn."
L["options_toggle_alpaca_voldun_desc"] = "Show locations for Elusive Quickhoof spawns."
L["options_toggle_alpaca_voldun"] = "Elusive Quickhoof"
------------------------------------ GEAR -------------------------------------
L["warglaive"] = "战刃"
---------------------------------- TOOLTIPS -----------------------------------
L["in_small_cave"] = "在小洞穴。"
L["in_water_cave"] = "在水下洞穴。"
---------------------------------- VISIBILITY ---------------------------------
L["options_toggle_chests_desc"] = "顯示寶箱位置 (每日可拾取的)。"
L["options_toggle_chests"] = "寶箱"
-- Shrines
L["Shrine of Nature"] = "自然聖壇"
L["Laribole"] = "萊里柏石"
L["Shrine of the Dawning"] = "黎明聖壇"
L["Scarlet Diamond"] = "血紅鑽石"
L["Shrine of the Sands"] = "沙塵聖壇"
L["Amberblaze"] = "烈焰琥珀"
L["Shrine of the Sea"] = "海濤聖壇"
L["Royal Quartz"] = "皇家石英"
L["Shrine of the Eventide"] = "黃昏聖壇"
L["Tidal Amethyst"] = "海潮紫晶"
L["Shrine of Storms"] = "風雨聖壇"
L["Owlseye"] = "鶚眼石"
-- Waypoints
L["Create all waypoints"] = "創建所有路徑點"
-- Options
L["These settings control the look of the icon."] = "這些設定控制圖示的外觀。"
L["Show Shrines"] = "顯示聖壇"
L["Show Shrines which Jewelercrafters can use to create gems"] = "顯示那些珠寶學者可以創造珠寶的聖壇"
--config.options
L["HandyNotes: TravelGuide"] = true
L["What to display?"] = true
L["These settings control what type of icons to be displayed."] = true
L["Boat"] = true
L["Show the boat locations."] = true
L["Horde Boat"] = true
L["Show the Horde boat locations."] = true
L["Alliance Boat"] = true
L["Show the Alliance boat locations."] = true
L["Zeppelin"] = true
L["Show the Zeppelin locations."] = true
L["Horde Zeppelin"] = true
L["Show the Horde Zeppelin locations."] = true
L["Alliance Zeppelin"] = true
L["Show the Alliance Zeppelin locations."] = true
L["Note"] = true
L["Show the node's additional notes when it's available."] = true
L["Show the portal locations."] = true
L["Order Hall portal"] = true
L["Show the Order Hall portal locations."] = true
L["Warfront portal"] = true
L["Show the Warfront portal locations."] = true
L["Deeprun Tram"] = true
L["Show the Deeprun Tram locations in Stormwind and Ironforge."] = true
L["Others"] = true
L["Show all the other POIs."] = true
--Plugin_config
L["AddOn Settings"] = true
L["Query from server"] = true
L["Send query request to server to lookup localized name. May be a little bit slower for the first time lookup but would be very fast once the name is found and cached."] = true
L["Restore hidden nodes"] = true
L["Show all nodes that you manually hid by right-clicking on them and choosing \"Hide this node\"."] = true
L["All hidden nodes have been restored"] = true
--Handler
L["Shows the portal, zepplin and boat locations on the World Map and the MiniMap."] = true
L["TravelGuide"] = true
L["Requires at least player level: "] = true
L["Unlocked with quest: ["] = true
L["RETRIEVING DATA..."] = true
L["Add to TomTom"] = true
L["Hide this node"] = true
--DB
--BFA
L["Zandalar"] = true
L["Zandalar, Zuldazar"] = true
L["Portal to Zuldazar"] = true
L["Boat to Zuldazar"] = true
L["Return to Zuldazar"] = true
L["Boat to Vol'Dun"] = true
L["Boat to Nazmir"] = true
L["Portal to Nazjatar"] = true
L["Submarine to Mechagon"] = true
L["Portal to Silithus"] = true
L["Kul Tiras"] = true
L["Kul Tiras, Tiragarde Sound"] = true
L["Portal to Boralus"] = true
L["Boat to Boralus"] = true
L["Return to Boralus"] = true
L["Boat to Drustvar"] = true
L["Boat to Stormsong Valley"] = true
L["Boat to Tiragarde Sound"] = true
L["Portal to Arathi Highlands"] = true
L["Portal to Port of Zandalar"] = true
L["Portal to Darkshore"] = true
L["Portal to Port of Boralus"] = true
L["currently NOT available"] = true
--Legion
L["Broken Isles"] = true
L["Broken Isles, Stormheim"] = true
L["Portal to Stormheim"] = true
L["Portal to Helheim"] = true
L["Portal to Dalaran"] = true
L["Portal to Azsuna"] = true
L["Portal to Emerald Dreamway"] = true
L["Great Eagle to Trueshot Lodge"] = true
L["Jump to Skyhold"] = true
L["Dalaran"] = true
L["Azsuna"] = true
L["Val'sharah"] = true
L["Suramar"] = true
L["Highmountain"] = true
L["Stormheim"] = true
--WoD
L["Portal to Warspear"] = true
L["Portal to Stormshield"] = true
L["Portal to Vol'mar"] = true
L["Portal to Lion's watch"] = true
L["Draenor, Tanaan Jungle"] = true
L["Draenor, Ashran"] = true
--MoP
L["Pandaria"] = true
L["Pandaria, Kun-Lai Summit"] = true
L["Pandaria, Townlong Steppes"] = true
L["Portal to Jade Forest"] = true
L["Portal to Pandaria"] = true
L["Portal to Isle of Thunder"] = true
L["Portal to Shado-Pan Garrison"] = true
L["Portal to Peak of Serenity"] = true
--Cata
L["Maelstrom"] = true
L["Maelstrom, Deepholm"] = true
L["Portal to Deepholm"] = true
L["Portal to Temple of Earth"] = true
L["Portal to Therazane's Throne"] = true
L["Portal to Twilight Highlands"] = true
L["Portal to Tol Barad"] = true
L["Portal to Uldum"] = true
L["Portal to Vashj'ir"] = true
L["Portal to Hyjal"] = true
--WotLK
L["Northrend, Crystalsong Forest"] = true
L["Portal to the Purple Parlor"] = true
L["Northrend, Howling Fjord"] = true
L["Northrend, Vengeance Landing"] = true
L["Northrend, Valgarde"] = true
L["Boat to Howling Fjord"] = true
L["Boat to Kamagua"] = true
L["Portal to Howling Fjord"] = true
L["Northrend, Borean Tundra"] = true
L["Northrend, Warsong Hold"] = true
L["Northrend, Valiance Keep"] = true
L["Boat to Borean Tundra"] = true
L["Boat to Unu'Pe"] = true
L["Zeppelin to Borean Tundra"] = true
L["Northrend, Dragonblight"] = true
L["Boat to Moa'Ki Harbor"] = true
--BC
L["Outland"] = true
L["Outland, Terokkar Forest"] = true
L["Portal to Hellfire Peninsula"] = true
L["Portal to Shattrath"] = true
L["Portal to Isle of Quel'Danas"] = true
L["Kalimdor, Azuremyst Isle"] = true
L["Portal to Exodar"] = true
L["in Exodar"] = true
L["Boat to Exodar"] = true
--Vanilla
L["Eastern Kingdoms"] = true
L["Eastern Kingdoms, Wetlands"] = true
L["Boat to Menethil Harbor"] = true
L["Eastern Kingdoms, Eversong Woods"] = true
L["Portal to Silvermoon"] = true
L["Eastern Kingdoms, Tirisfal Glades"] = true
L["Portal to Undercity"] = true
L["Orb of translocation"] = true
L["in Undercity Magic Quarter"] = true
L["Eastern Kingdoms, Stranglethorn Vale"] = true
L["Eastern Kingdoms, Grom'gol Base Camp"] = true
L["Zeppelin to Stranglethorn Vale"] = true
L["Portal to Stranglethorn Vale"] = true
L["Boat to Booty Bay"] = true
L["Eastern Kingdoms, Elwynn Forest"] = true
L["Portal to Stormwind"] = true
L["Boat to Stormwind"] = true
L["Deeprun Tram to Stormwind"] = true
L["Eastern Kingdoms, Dun Morogh"] = true
L["Portal to Ironforge"] = true
L["Deeprun Tram to Ironforge"] = true
L["Kalimdor"] = true
L["Kalimdor, Durotar"] = true
L["Portal to Orgrimmar"] = true
L["Zeppelin to Orgrimmar"] = true
L["Kalimdor, Mulgore"] = true
L["Portal to Thunder Bluff"] = true
L["Zeppelin to Thunder Bluff"] = true
L["Kalimdor, Teldrassil"] = true
L["Portal to Darnassus"] = true
L["Kalimdor, Northern Barrens"] = true
L["Boat to Ratchet"] = true
L["Kalimdor, Dustwallow Marsh"] = true
L["Boat to Theramore"] = true
L["Kalimdor, Tanaris"] = true
L["Portal to Caverns of Time"] = true
L["Eastern Kingdoms, Arathi Highlands"] = true
L["Kalimdor, Darkshore"] = true
L["config_auctioneer"] = "拍賣場"
L["config_auctioneer_desc"] = "顯示拍賣場的位置。"
L["config_banker"] = "銀行"
L["config_banker_desc"] = "顯示拍銀行的位置。"
L["config_barber"] = "美容院"
L["config_barber_desc"] = "顯示美容院的位置。"
L["config_easy_waypoints"] = "快速導航"
L["config_easy_waypoints_desc"] = "簡化建立路線導航的方法，只要點一下滑鼠右鍵便能設定導航目的地，CTRL + 右鍵點擊會有更多選項。"
L["config_icon_alpha"] = "圖示透明度"
L["config_icon_alpha_desc"] = "圖示的透明度。"
L["config_icon_scale"] = "圖示大小"
L["config_icon_scale_desc"] = "圖示的縮放大小。"
L["config_innkeeper"] = "旅店"
L["config_innkeeper_desc"] = "顯示旅店的位置。"
L["config_mail"] = "郵箱"
L["config_mail_desc"] = "顯示郵箱的位置。"
L["config_onlymytrainers"] = "只顯示我的專業相關的訓練師和商人"
L["config_onlymytrainers_desc"] = [[
只會影響主要專業的訓練師和商人。

|cFFFF0000注意: 只有兩個主要專業都學會了以後才有效果。|r
]]
L["config_others"] = "其他"
L["config_others_desc"] = "顯示其他所有的地圖探索點。"
L["config_plugin_desc"] = "在世界地圖和小地圖中顯示奧睿博司的 NPC 和地圖探索點的位置。"
L["config_plugin_name"] = "奧睿博司"
L["config_portal"] = "傳送門"
L["config_portal_desc"] = "顯示傳送門或傳送點的位置。"
L["config_reforge"] = "護甲強化"
L["config_reforge_desc"] = "顯示護甲強化的位置。"
L["config_restore_nodes"] = "恢復被隱藏的地圖探索點"
L["config_restore_nodes_desc"] = "恢復所有點右鍵選擇隱藏的地圖探索點。"
L["config_restore_nodes_print"] = "所有被隱藏的地圖探索點都已恢復"
L["config_stablemaster"] = "獸欄管理員"
L["config_stablemaster_desc"] = "顯示獸欄管理員的位置。"
L["config_tab_general"] = "一般"
L["config_tpplatforms"] = "傳送平台"
L["config_tpplatforms_desc"] = "顯示傳送平台的位置。"
L["config_trainer"] = "專業訓練師"
L["config_trainer_desc"] = "顯示專業訓練師的位置。"
L["config_transmogrifier"] = "塑形師"
L["config_transmogrifier_desc"] = "顯示塑形師的位置。"
L["config_travelguide_note"] = "|cFFFF0000*已透過 HandyNotes: TravelGuide 啟動。|r"
L["config_vendor"] = "商人"
L["config_vendor_desc"] = "顯示商人的位置。"
L["config_void"] = "虛空倉庫"
L["config_void_desc"] = "顯示虛空倉庫的位置。"
L["config_what_to_display"] = "選擇要顯示什麼"
L["config_what_to_display_desc"] = "這些設定控制要顯示哪類的圖示。"
L["dev_config_force_nodes"] = "強制顯示地圖點"
L["dev_config_force_nodes_desc"] = "強制顯示所有的地圖探索點，不論職業、陣營或誓盟。"
L["dev_config_show_prints"] = "顯示 print()"
L["dev_config_show_prints_desc"] = "在聊天視窗中顯示 print() 的訊息。"
L["dev_config_tab"] = "開發"
L["handler_context_menu_add_tomtom"] = "加入 TomTom"
L["handler_context_menu_addon_name"] = "地圖標記: 奧睿博司"
L["handler_context_menu_hide_node"] = "隱藏這個地圖點"
L["handler_tooltip_data"] = "正在取得資料..."
L["handler_tooltip_quest"] = "解鎖任務"
L["handler_tooltip_requires"] = "需要"
L["handler_tooltip_requires_level"] = "需要玩家等級"
L["handler_tooltip_sanctum_feature"] = "聖所升級"
L["handler_tooltip_TNTIER"] = "傳送網路第 %s 層。"
L["Into the Maw"] = "進入淵喉"
L["Mailbox"] = "郵箱"
L["Portal to Orgrimmar"] = "奧格瑪傳送門"
L["Portal to Stormwind"] = "暴風城傳送門"
L["To Ring of Fates"] = "前往命運之環"
L["To Ring of Transference"] = "前往樞運之環"


-------------------------------------------------------------------------------
----------------------------------- DRUSTVAR ----------------------------------
-------------------------------------------------------------------------------

L["ancient_sarco_note"] = nil
L["beshol_note"] = nil
L["cottontail_matron_note"] = nil
L["gluttonous_yeti_note"] = nil
L["idej_note"] = nil
L["seething_cache_note"] = nil
L["the_caterer_note"] = nil
L["vicemaul_note"] = nil

L["merchants_chest_note"] = nil
L["wicker_pup_note"] = nil

L["runebound_cache_note"] = nil
L["runebound_chest_note"] = nil
L["runebound_coffer_note"] = nil

L["captain_hermes_note"] = nil
L["dilbert_mcclint_note"] = nil
L["fizzie_spark_note"] = nil
L["michael_skarn_note"] = nil

L["drust_facts_note"] = nil
L["stele_forest_note"] = nil
L["options_icons_drust_facts_desc"] = nil
L["options_icons_drust_facts"] = nil

L["embers_crossbow_note"] = nil
L["embers_flask_note"] = nil
L["embers_hat_note"] = nil
L["embers_knife_note"] = nil
L["embers_golvar_note"] = nil
L["golvar_ruins"] = nil
L["options_icons_ember_relics_desc"] = nil
L["options_icons_ember_relics"] = nil

L["linda_deepwater_note"] = nil

-------------------------------------------------------------------------------
----------------------------------- MECHAGON ----------------------------------
-------------------------------------------------------------------------------

L["avenger_note"] = "當奧格索普‧奧布諾提斯是訪客時，殺死OOX-Fleetfoot/MG (區域滿地跑)來重生。"
L["beastbot_note"] = "在帕斯卡K1N6型製作一個［野獸機器人動力包］來啟動。"
L["cogstar_note"] = "殺死區域內任何地方的升級版哨衛，直到他傳送進來加強小怪。"
L["crazed_trogg_note"] = "在邦多的機械廠裡使用噴塗機，塗滿油漆的氣囊或機器人，用他大喊的顏色塗上自己。"
L["deepwater_note"] = "在帕斯卡K1N6型製作一個［百噚誘餌］來召喚。"
L["doppel_note"] = '從每日任務＂輪狂的建造狂熱＂獲得［減壓閥］，與其他兩名玩家一起啟動。'
L["foul_manifest_note"] = "連接水中的電塔到外圍電塔通電，然後到旁邊山坡上找到開關按下就會出現。"
L["furor_note"] = '在每日任務 "來自諾達希爾的協助" 期間，點擊小藍色蘑菇直到出現。'
L["killsaw_note"] = "在飛逝森林的任何地方出現，似乎殺死鋸刃伐木機器人後比較容易出現。不會在風險投資公司在森林裡的時候出現，那時候沒有伐木機器人。"
L["leachbeast_note"] = "使用［發熱蒸發器線圈］啟動天氣改變裝置，天氣轉為下雨後，擊殺一定數量的濾液怪出現。"
L["nullifier_note"] = '使用藍色卡片－[遠距迴路旁通器] 或是DNT-碰撞轉移裝置駭入啟動。前者為廢料王掉落，後者為鑽探機JD41與JD99的小怪掉落。'
L["scrapclaw_note"] = "離岸在水中。"
L["sparkqueen_note"] = '當每日任務＂有蟲.好多蟲!＂期間，殺死一定數量蜘蛛出現。'
L["rusty_note"] = "在帕斯卡K1N6型上製作一個［個人時光移轉裝置］，以進入不同的未來。只有當克羅米不是訪客時才會出現。"
L["vaultbot_note"] = "風箏到邦多的機械廠的特斯拉線圈，或在帕斯卡K1N6型上製作一個保險庫機器人鑰匙來直接打開。"

L["iron_chest"] = "鐵潮帶鎖箱"
L["mech_chest"] = "機械箱"
L["msup_chest"] = "機械補給箱"
L["rust_chest"] = "老舊生鏽箱子"
L["iron_chest_note"] = "開啟鐵潮帶鎖箱的鑰匙從西湧列島小怪掉落。"
L["msup_chest_note"] = "開啟機械補給箱的鑰匙從西湧列島小怪掉落。"
L["rust_chest_note"] = "開啟老舊生鏽箱子的鑰匙從西湧列島小怪掉落。"

L["rec_rig_note"] = "要啟動困難模式，使用超級對撞機武器來將所有輻射元素轉換為不穩定輻射元素。寵物可以在兩種難度中獲得。"

L["grease_bot_note"] = nil
L["shock_bot_note"] = nil
L["welding_bot_note"] = nil

L["options_icons_mech_buffs"] = nil
L["options_icons_mech_buffs_desc"] = nil
L["options_icons_mech_chest"] = "機械化箱"
L["options_icons_mech_chest_desc"] = "顯示機械化箱子的位置。有10個獨特的箱子可以每天洗一次，每個箱子有4-5個產卵位置。位置按顏色分組。"
L["options_icons_locked_chest"] = "鎖定箱子"
L["options_icons_locked_chest_desc"] = "在西湧列島中顯示上鎖箱子的位置。"
L["options_icons_recrig"] = "廢料回收機"
L["options_icons_recrig_desc"] = "顯示廢料回收機的位置以及事件獎賞。"

-------------------------------------------------------------------------------
----------------------------------- NAZJATAR ----------------------------------
-------------------------------------------------------------------------------

L["naz_intro_note"] = "完成入門任務鏈，解鎖Nazjatar上的rares，寶藏和世界任務。"

L["alga_note"] = "注意: 被四個小怪遮掩！"
L["allseer_note"] = "在卡美伊爾低層的任何地方出現。"
L["anemonar_note"] = "在它上方擊殺巨大的擎天魟來啟動。"
L["avarius_note"] = "使用鹵石鎬收集並將彩色晶體放在基座上。 你不必是一個礦工！"
L["banescale_note"] = "有很小的機率在殺死群母後立即出現。"
L["elderunu_note"] = "在卡美伊爾高層的任何地方出現。"
L["gakula_note"] = "驅趕血鳍蝌蚪直到它出現。"
L["glimmershell_note"] = "有小機率出現在微光殼巨蟹的位置。"
L["kelpwillow_note"] = "使用棱彩水晶魅惑［淤泥蛞蝓］後帶給它來啟動。"
L["lasher_note"] = "在土壤中種植發芽的種子並餵養蒼蠅。"
L["matriarch_note"] = "與另外兩位族母共享重生計時器。"
L["needle_note"] = "通常出現在［女王之門］區域。"
L["oronu_note"] = "到沉默市場找到NPC購買［溺水幼鷹獸］寵物帶著它靠近後就可啟動。"
L["rockweed_note"] = "殺死整個區域的失落的Algan和Wayward Algan直到他出現。 建議使用團隊，因為這可能是一個長期的苦工作。"
L["sandcastle_note"] = "使用顯現石在區域內的任何地方顯露寶箱直到它出現。"
L["tidelord_note"] = "殺死三個艾薩利塑能師以及招喚的被釋放的狂潮直到浪潮領主被召喚出來。"
L["tidemistress_note"] = "點擊未受干擾的樣本直到她出現。"
L["urduu_note"] = "在它面前重疊擊殺［鹿角暗礁行者］後來啟動。"
L["voice_deeps_notes"] = "使用脫下來的殼來衝破此岩石。"
L["vorkoth_note"] = "把餌食扔進池中直到它出現。"
L["area_spawn"] = "在周邊地區出現。"
L["cora_spawn"] = "在珊瑚林的任何地方出現。"
L["cave_spawn"] = "在洞穴中出現。"
L["east_spawn"] = "在區域的東半邊任何地方出現。"
L["ucav_spawn"] = "在水下的洞穴出現。"
L["zone_spawn"] = "在整個區域出現。"

L["assassin_looted"] = "當為刺客時可以拾取。"

L["arcane_chest"] = "祕法寶箱"
L["glowing_chest"] = "發光的祕法寶箱"
L["arcane_chest_01"] = "在一些海藻下。"
L["arcane_chest_02"] = "在建築內部的上層"
L["arcane_chest_03"] = "在第二層。"
L["arcane_chest_04"] = "在瀑布上方的水中。"
L["arcane_chest_05"] = "在廢墟中。"
L["arcane_chest_06"] = "" -- in the open
L["arcane_chest_07"] = "在洞穴的後面。入口位於贊季爾沙灘東邊。"
L["arcane_chest_08"] = "藏在一些海星下面。"
L["arcane_chest_09"] = "在珍珠殼爬行者(暫譯)後面的一個洞穴裡。"
L["arcane_chest_10"] = "在一個脫下來的殼下面。"
L["arcane_chest_11"] = "在山丘的頂部。"
L["arcane_chest_12"] = "在瀑布的頂部。"
L["arcane_chest_13"] = "在懸崖的頂部，在樹後面。"
L["arcane_chest_14"] = "在伊露恩諾神殿內部。"
L["arcane_chest_15"] = "在建築物的右側。"
L["arcane_chest_16"] = "在水下的洞穴，入口在南方。"
L["arcane_chest_17"] = "在瀑布的頂部。"
L["arcane_chest_18"] = "在路徑下方的一個洞穴裡。"
L["arcane_chest_19"] = "在岩石拱門的頂部。 使用滑翔翼（或是飛行）"
L["arcane_chest_20"] = "在山的頂部。"
L["glowing_chest_1"] = "在水下洞穴的後面，防衛鐵塔。"
L["glowing_chest_2"] = "解開線條。"
L["glowing_chest_3"] = "在洞穴的後面。防衛鐵塔。"
L["glowing_chest_4"] = "消掉三個紅色符文。"
L["glowing_chest_5"] = "在洞穴，防衛鐵塔。"
L["glowing_chest_6"] = "解開線條。"
L["glowing_chest_7"] = "消掉四個藍色符文。"
L["glowing_chest_8"] = "在屋頂上。防衛鐵塔。"

L["prismatic_crystal_note"] = nil
L["strange_crystal"] = nil
L["strange_crystal_note"] = nil
L["options_icons_prismatics"] = nil
L["options_icons_prismatics_desc"] = nil

L["slimy_cocoon"] = "軟泥的卵"
L["ravenous_slime_note"] = "使用棱彩水晶控制小動物餵養軟泥。重複五天，直到它產生一個帶有寵物的卵。軟泥將一直持續到下一周重置。"
L["slimy_cocoon_note"] = "一隻寵物準備從卵中收集！ 如果在您的階段它沒有出現，那麼卵的冷卻時間就會消失。 更改階段或稍後再回來查看。"

L["cat_figurine"] = "水晶貓雕像"
L["cat_figurine_01"] = "在一個水下洞穴。雕像在露天的地板上。入口在東邊。"
L["cat_figurine_02"] = "在附近瀑布下的一個洞穴裡。 雕像在牆上的海星下面。"
L["cat_figurine_03"] = "在一個水下洞穴。雕像被藏在某些破碎的貝殼下。"
L["cat_figurine_04"] = "在一個水下洞穴。雕像在露天的地板上。"
L["cat_figurine_05"] = "在一個小洞穴。雕像隱藏在地板上的植物後面。"
L["cat_figurine_06"] = "在一個充滿敵對的礁石行者的水下洞穴中。 小雕像在牆上。 入口在北方。"
L["cat_figurine_07"] = "在一個小洞穴。雕像在一些珊瑚的牆上。"
L["cat_figurine_08"] = "在一個小洞穴。躲避祕法圈。 小雕像在後面的高大的岩石上。"
L["cat_figurine_09"] = "在一個水下洞穴。雕像位於天花板的岩石拱門上。"
L["cat_figurine_10"] = "在路徑下方的一個洞穴裡。 雕像在三個桶之間。"
L["figurines_found"] = nil

L["mardivas_lab"] = "瑪爾迪瓦斯實驗室"
L["no_reagent"] = "不使用水晶"
L["swater"] = "小深海"
L["gwater"] = "大深海"
L["sfire"] = "小火炎"
L["gfire"] = "大火炎"
L["searth"] = "小土岩"
L["gearth"] = "大土岩"
L["Arcane"] = nil
L["Watery"] = nil
L["Burning"] = nil
L["Dusty"] = nil
L["Zomera"] = nil
L["Omus"] = nil
L["Osgen"] = nil
L["Moghiea"] = nil
L["Xue"] = nil
L["Ungormath"] = nil
L["Spawn"] = nil
L["Herald"] = nil
L["Salgos"] = nil
L["tentacle_taco"] = "出售 {item:170100} 如果你是穿著艾薩利怒濤者斗篷。"

L["options_icons_slimes_nazj"] = "飢餓的軟泥"
L["options_icons_slimes_nazj_desc"] = "顯示已經餵養可以產出戰寵的四種飢餓軟泥的位置。"
L["options_icons_cats_nazj"] = "貓咪雕像"
L["options_icons_cats_nazj_desc"] = "顯示'喵出喵咪喵像'成就的水晶貓位置。"
L["options_icons_misc_nazj"] = "其他"
L["options_icons_misc_nazj_desc"] = "顯示莫洛哥的洞穴以及瑪爾迪瓦斯的實驗室的位置。"

-------------------------------------------------------------------------------
------------------------------------ NAZMIR -----------------------------------
-------------------------------------------------------------------------------

L["captain_mukala_note"] = nil
L["enraged_water_note"] = nil
L["lucille_note"] = nil
L["offering_to_bwonsamdi_note"] = nil
L["shambling_ambusher_note"] = nil
L["zaamar_note"] = nil

L["grady_prett_note"] = nil
L["korval_dark_note"] = nil
L["lozu_note"] = nil

L["tales_bwonsamdi_note"] = nil
L["tales_hireek_note"] = nil
L["tales_kragwa_note"] = nil
L["tales_torga_note"] = nil

L["carved_in_stone_41860"] = nil
L["carved_in_stone_41861"] = nil
L["carved_in_stone_41862"] = nil
L["carved_in_stone_42116"] = nil
L["options_icons_carved_in_stone"] = nil
L["options_icons_carved_in_stone_desc"] = nil

L["hoppin_sad_53419"] = nil
L["hoppin_sad_53420"] = nil
L["hoppin_sad_53424"] = nil
L["hoppin_sad_53425"] = nil
L["hoppin_sad_53426"] = nil

L["options_icons_hoppin_sad"] = nil
L["options_icons_hoppin_sad_desc"] = nil

-------------------------------------------------------------------------------
------------------------------- STORMSONG VALLEY ------------------------------
-------------------------------------------------------------------------------

L["in_basement"] = nil
L["jakala_note"] = nil
L["nestmother_acada_note"] = nil
L["sabertron_note"] = nil
L["whiplash_note"] = nil

L["discarded_lunchbox_note"] = nil
L["hidden_scholars_chest_note"] = nil
L["honey_vat"] = nil
L["smugglers_stash_note"] = nil
L["sunken_strongbox_note"] = nil
L["venture_co_supply_chest_note"] = nil
L["weathered_treasure_chest_note"] = nil

L["curious_grain_sack"] = nil
L["small_treasure_chest"] = nil
L["small_treasure_51927"] = nil
L["small_treasure_51940"] = nil

L["eddie_fixit_note"] = nil
L["ellie_vern_note"] = nil
L["leana_darkwind_note"] = nil

L["honeyback_harvester_note"] = nil
L["options_icons_honeybacks"] = nil
L["options_icons_honeybacks_desc"] = nil

L["lets_bee_friends_note"] = nil
L["lets_bee_friends_step_1"] = nil
L["lets_bee_friends_step_2"] = nil
L["lets_bee_friends_step_3"] = nil
L["lets_bee_friends_step_4"] = nil
L["lets_bee_friends_step_5"] = nil

L["these_hills_sing_note"] = nil

L["ancient_tidesage_scroll"] = nil
L["ancient_tidesage_scroll_note"] = nil
L["options_icons_tidesage_legends"] = nil
L["options_icons_tidesage_legends_desc"] = nil

L["long_forgotten_rum_note"] = nil

-------------------------------------------------------------------------------
------------------------------- TIRAGARDE SOUND -------------------------------
-------------------------------------------------------------------------------

L["honey_slitherer_note"] = nil
L["tempestria_note"] = nil
L["twin_hearted_note"] = nil
L["wintersail_note"] = nil

L["hay_covered_chest_note"] = nil
L["pirate_treasure_note"] = nil

L["damp_scroll"] = nil
L["damp_scroll_note_1"] = nil
L["damp_scroll_note_2"] = nil
L["damp_scroll_note_3"] = nil
L["damp_scroll_note_4"] = nil
L["damp_scroll_note_5"] = nil
L["ominous_altar"] = nil
L["ominous_altar_note"] = nil
L["secret_of_the_depths_note"] = nil

L["burly_note"] = nil
L["delia_hanako_note"] = nil
L["kwint_note"] = nil

L["shanty_fruit_note"] = nil
L["shanty_horse_note"] = nil
L["shanty_inebriation_note"] = nil
L["shanty_lively_note"] = nil
L["options_icons_shanty_raid"] = nil
L["options_icons_shanty_raid_desc"] = nil

L["upright_citizens_node"] = nil
L["options_icons_upright_citizens"] = nil
L["options_icons_upright_citizens_desc"] = nil

-------------------------------------------------------------------------------
------------------------------------ ULDUM ------------------------------------
-------------------------------------------------------------------------------

L["uldum_intro_note"] = "完成前置引導任務鏈，以解鎖奧丹姆中的稀有物品，寶藏和攻擊任務。"

L["aqir_flayer"] = "與亞基蟲巢工人以及亞基收割者共用出生點。"
L["aqir_titanus"] = "與亞基巨怪共用出生點。"
L["aqir_warcaster"] = "與亞基虛無法師共用出生點。"
L["atekhramun"] = "壓碎附近的毒鱗幼蠍直到出現。"
L["chamber_of_the_moon"] = "在月之大廳地下。"
L["chamber_of_the_stars"] = "在眾星之間地下。"
L["chamber_of_the_sun"] = "在日陽之間裡面。"
L["dunewalker"] = "在上面的平台上點擊“太陽精華”以釋放他。"
L["friendly_alpaca"] = "餵七次羊駝吉薩爾草，以作為坐騎收藏。 在一個位置出現10分鐘，然後很久後才重生。"
L["gaze_of_nzoth"] = "與汙穢觀察者共用出生點。"
L["gersahl_note"] = "餵給友善的羊駝七次獲得坐騎。 不需要草藥學。"
L["gersahl"] = "吉薩爾草叢"
L["hmiasma"] = "餵食它周圍的軟泥，直到它啟動。"
L["kanebti"] = "從一個珠寶古墓聖甲蟲中收集一個珠寶聖甲蟲小雕像，該雕像與普通的古墓聖甲蟲共用出生點。 將雕像插入聖甲蟲聖壇以召喚稀有怪。"
L["neferset_rare"] = "這六個稀有怪在奈斐賽特具有相同的三個出生位置。 完成許多“召喚儀式”事件後，將隨機產生三個。"
L["platform"] = "出生在浮動平台頂部。"
L["right_eye"] = "放下全知之眼玩具的右半部分。"
L["single_chest"] = "此箱子僅在一個位置產生！ 如果不存在，請稍等一下，它將重新生成。"
L["tomb_widow"] = "當柱子上出現白色卵囊時，殺死隱形的蜘蛛來召喚。"
L["uatka"] = "與其他兩個玩家一起，點擊每個神秘設備。 需要來自阿瑪賽特聖匣的觸日者護符。"
L["wastewander"] = "與廢土漫遊者隊長共用出生點。"

L["amathet_cache"] = "阿瑪賽特寶箱"
L["black_empire_cache"] = "黑暗帝國寶箱"
L["black_empire_coffer"] = "黑暗帝國大寶箱"
L["infested_cache"] = "被感染的儲藏箱"
L["infested_strongbox"] = "被感染的保險箱"
L["amathet_reliquary"] = "阿瑪賽特聖匣"

L["options_icons_assault_events"] = "突擊事件"
L["options_icons_assault_events_desc"] = "顯示突擊事件可能的位置。"
L["options_icons_coffers"] = "上鎖的大寶箱"
L["options_icons_coffers_desc"] = "顯示上鎖的大寶箱的位置 (每次突擊只能拾取一次)。"

L["ambush_settlers"] = "打敗一波波的怪物，直到事件結束。"
L["burrowing_terrors"] = "跳起來將穴居甲蟲它們壓扁。"
L["call_of_void"] = "淨化儀式柱。"
L["combust_cocoon"] = "將土製火焰彈扔在天花板上的繭上。"
L["dormant_destroyer"] = "點擊所有虛空導管晶體。"
L["executor_nzoth"] = "殺死恩若司的執行者，然後摧毀執行者之錨。"
L["hardened_hive"] = "拿起地上的廢土火焰噴射器並燃燒所有的卵囊。"
L["in_flames"] = "拿起水桶，撲滅火焰。"
L["monstrous_summon"] = "殺死所有深淵先驅者以停止召喚。"
L["obsidian_extract"] = "摧毀所有虛空形成的黑曜石晶體。"
L["purging_flames"] = "撿起屍體，扔進火裡。"
L["pyre_amalgamated"] = "淨化材堆，然後殺死所有的小怪直到血肉融合體出現。"
L["ritual_ascension"] = "殺死日觸祭儀師。"
L["solar_collector"] = "在收集器的所有側面啟用所有五個單元。 單擊一個單元也會切換所有鄰近的單元。"
L["summoning_ritual"] = "殺死侍僧，然後關閉召喚傳送門。事件多次完成後，奈斐賽特周圍將產生一組三種稀有。"
L["titanus_egg"] = "消滅巨怪卵，然後擊敗精英怪年幼巨蟲，打不過就拉去旁邊階梯下讓NPC幫忙"
L["unearthed_keeper"] = "消滅出土的守衛者。"
L["virnall_front"] = "擊敗一波波的小怪，直到戰爭使者麥尼普塔出現。"
L["voidflame_ritual"] = "熄滅所有虛無之觸蠟燭。"

L["beacon_of_sun_king"] = "向內旋轉所有三個雕像。"
L["engine_of_ascen"] = "將所有四個雕像移入光束。"
L["lightblade_training"] = "殺死導師和新進者，直到『拂曉之刃』卡姆斯出生為止。"
L["raiding_fleet"] = "使用任務物品燃燒所有船隻。"
L["slave_camp"] = "打開附近的所有籠子。"
L["unsealed_tomb"] = "保護黑魯免遭怪物的襲擊。"

-------------------------------------------------------------------------------
------------------------------------ VALE -------------------------------------
-------------------------------------------------------------------------------

L["vale_intro_note"] = "完成前置引導任務鏈，以解鎖恆春谷中的稀有物品，寶藏和攻擊任務。"

L["big_blossom_mine"] = "在繁花礦坑內，入口在東北。"
L["guolai"] = "在郭萊院中。"
L["guolai_left"] = "在郭萊院中 (左邊通道)。"
L["guolai_center"] = "在郭萊院中 (中央通道)。"
L["guolai_right"] = "在郭萊院中 (右邊通道)。"
L["left_eye"] = "放下全知之眼玩具的左半部分。"
L["pools_of_power"] = "在能量之池中，入口在黃金寶塔。"
L["tisiphon"] = "點擊丹妮爾的幸運釣竿。"

L["ambered_cache"] = "琥珀化寶箱"
L["ambered_coffer"] = "琥珀寶庫"
L["mogu_plunder"] = "魔古的財寶"
L["mogu_strongbox"] = "魔古寶箱"

L["abyssal_ritual"] = "殺死沉沒的擁護者然後殺死深淵巨怪。"
L["bound_guardian"] = "殺死三隻淵裔束縛者以釋放純淨水滴。"
L["colored_flames"] = "從火把上收集彩色火焰，並帶到相對應的符文上。"
L["construction_ritual"] = "將猛虎雕像推入光束中。"
L["consuming_maw"] = "淨化生長物和觸手，直到被踢出。"
L["corruption_tear"] = "點擊抓起一旁的巨大信標，在不讓旋轉的眼睛撞到你的情況下關閉裂口。"
L["electric_empower"] = "殺死參天呼換者，然後殺死『灌注者』馬奈可。"
L["empowered_demo"] = "關閉所有靈神聖匣"
L["empowered_wagon"] = "拿起影潘爆彈，將其放在戰車下方。"
L["feeding_grounds"] = "摧毀琥珀瓶和懸浮密室。"
L["font_corruption"] = "旋轉魔古雕像，直到兩個光束都到達後方，然後點擊控制台。"
L["goldbough_guardian"] = "保護族長金枝免受一波波怪物的襲擊。"
L["infested_statue"] = "將所有扭曲之眼從雕像上移開。"
L["kunchong_incubator"] = "摧毀所有力場產生器。"
L["mantid_hatch"] = "拿起影潘火焰噴射器並摧毀幼蟲孵化器。"
L["mending_monstro"] = "摧毀所有三個一組療癒琥珀。"
L["mystery_sacro"] = "摧毀所有可疑墓碑，殺死哀號之魂。"
L["noodle_cart"] = "在阿欽修裡拉麵推車時保護他。"
L["protect_stout"] = "保護洞穴免遭怪物的襲擊。"
L["pulse_mound"] = "殺死周圍的生物，然後殺死成長活體"
L["ravager_hive"] = "摧毀樹上所有的蜂巢。"
L["ritual_wakening"] = "殺死卡拉西喚醒者。"
L["serpent_binding"] = "殺死參天征服者，然後殺死昊風。"
L["stormchosen_arena"] = "清除競技場中的所有小怪，然後殺死氏族將軍。"
L["swarm_caller"] = "摧毀喚蟲者柱子。"
L["vault_of_souls"] = "打開金庫，摧毀所有雕像。"
L["void_conduit"] = "點擊虛空導管並擠壓觀察的眼睛。"
L["war_banner"] = "燃燒戰旗並殺死小怪，直到指揮官出現。"
L["weighted_artifact"] = "拿起古怪的重花瓶，穿越迷宮回到基座放置，中途如果被雕像打中花瓶會掉落。"

-------------------------------------------------------------------------------
----------------------------------- VISIONS -----------------------------------
-------------------------------------------------------------------------------

L["colored_potion"] = "彩色藥水"
L["colored_potion_note"] = [[
％s屍體旁邊的藥水始終指示運行的負面效果藥水的顏色。

+100理智藥水的顏色可以由該藥水的顏色確定（| cFFFF0000壞 | r => | cFF00FF00好 | r）：

黑色 => 綠色
藍色 => 紫色
綠色 => 紅色
紫色 => 黑色
紅色 => 藍色
]]

L["bear_spirit_note"] = "殺死憤怒的熊地毯靈和所有小怪，即可獲得10％的加速增益。"
L["buffs_change"] = "可用的增益每次都會更換。 如果建築物關閉或缺少NPC/物體，則本次該增益沒有提供。"
L["clear_sight"] = "需要清除視線等級 %d。"
L["craggle"] = "將玩具放在地面上（例如玩具火車組）以分散他的注意力。 拉開他的機器人，並先殺死他們。"
L["empowered_note"] = "穿過地雷的迷宮，站在樓上的實驗增益礦上，獲得10％的傷害增益。"
L["enriched_note"] = "殺死被忽視的公會銀行，獲得10％暴擊增益。"
L["ethereal_essence_note"] = "殺死Warpweaver Dushar，獲得10％暴擊增益。(暫譯)"
L["ethereal_note"] = "收集隱藏在整個幻象內的橙色晶體，並將其返回該NPC以獲取額外的獎勵。總計有10個水晶每個區域兩個。\n\n| cFF00FF00別忘了拾取箱子！|r"
L["heroes_bulwark_note"] = "在旅館內殺死加蒙，獲得10％的生命增益。"
L["inside_building"] = "在建築物內。"
L["mailbox"] = "郵箱"
L["mail_muncher"] = "開啟以後，郵件咀嚼者有機會出現。(暫譯)"
L["odd_crystal"] = "奇怪的水晶"
L["requited_bulwark_note"] = "殺死Agustus Moulaine，可獲得7％的臨機應變增益。"
L["shave_kit_note"] = "在理髮店裡面，拾取桌上的箱子。"
L["smiths_strength_note"] = "在鐵匠小屋中殺死納羅斯，取得10％的傷害增益。"
L["spirit_of_wind_note"] = "殺死布旺巴獲得10％的加速和移動速度提升。"
L["void_skull_note"] = "點擊地面上的頭顱以拾取玩具。"

L["c_alley_corner"] = "在小巷的一個角落。"
L["c_bar_upper"] = "在酒吧的上層。"
L["c_behind_bank_counter"] = "在銀行櫃檯的後面。"
L["c_behind_boss"] = "在首領後方的流亡者建築。"
L["c_behind_boxes"] = "在一些盒子後面的角落。"
L["c_behind_cart"] = "在一輛被毀的推車後面。"
L["c_behind_house_counter"] = "在櫃檯後面的房子裡。"
L["c_behind_mailbox"] = "在郵箱後方。"
L["c_behind_pillar"] = "隱藏在使館大樓後方的支柱後面。"
L["c_behind_rexxar"] = "隱藏在雷克薩建築物後面的右側。"
L["c_behind_stables"] = "在肖爾的馬槽後。"
L["c_by_pillar_boxes"] = "在支柱和一些盒子之間的牆上。"
L["c_center_building"] = "在中心建築的底層。"
L["c_forge_corner"] = "在一個鍛造的角落。"
L["c_hidden_boxes"] = "隱藏在索爾建築後方的一些盒子後面。"
L["c_inside_auction"] = "在拍賣行內的右邊。"
L["c_inside_big_tent"] = "在大帳篷裡的左邊。"
L["c_inside_cacti"] = "在拐角處的仙人掌補丁裡。"
L["c_inside_hut"] = "在右邊的第一個小屋內。"
L["c_inside_leatherwork"] = "在製皮建築內。"
L["c_inside_orphanage"] = "在孤兒院裡。"
L["c_inside_transmog"] = "在塑形小屋內。"
L["c_left_cathedral"] = "隱藏在大教堂入口左側。"
L["c_left_inquisitor"] = "階梯左側的審訊官小首領的後面。"
L["c_on_small_hill"] = "在小山頂上。"
L["c_top_building"] = "在建築物的頂層。"
L["c_underneath_bridge"] = "在橋下。"
L["c_walkway_corner"] = "在角落的上層人行道上。"
L["c_walkway_platform"] = "在上走道上方的平台上。"

L["options_icons_visions_buffs"] = "增益"
L["options_icons_visions_buffs_desc"] = "顯示可以造成1小時傷害增強的事件的位置。"
L["options_icons_visions_chest"] = "寶箱"
L["options_icons_visions_chest_desc"] = "在驚懼幻象中顯示可能的寶箱位置。"
L["options_icons_visions_crystals"] = "奇怪的水晶"
L["options_icons_visions_crystals_desc"] = "在驚懼幻象中顯示奇怪的水晶位置。"
L["options_icons_visions_mail"] = "郵箱"
L["options_icons_visions_mail_desc"] = "顯示郵件咀嚼者坐騎的郵箱位置。"
L["options_icons_visions_misc"] = "其他"
L["options_icons_visions_misc_desc"] = "在驚懼幻象中顯示稀有、玩具、藥水和增強的位置。"

-------------------------------------------------------------------------------
----------------------------------- VOLDUN ------------------------------------
-------------------------------------------------------------------------------

L["bloodwing_bonepicker_note"] = nil
L["nezara_note"] = nil
L["vathikur_note"] = nil
L["zunashi_note"] = nil

L["ashvane_spoils_note"] = nil
L["excavators_greed_note"] = nil
L["grayals_offering_note"] = nil
L["kimbul_offerings_note"] = nil
L["sandsunken_note"] = nil

L["keeyo_note"] = nil
L["kusa_note"] = nil
L["sizzik_note"] = nil

L["tales_akunda_note"] = nil
L["tales_kimbul_note"] = nil
L["tales_sethraliss_note"] = nil

L["plank_1"] = nil
L["plank_2"] = nil
L["plank_3"] = nil
L["plank_4"] = nil
L["plank_5"] = nil
L["planks_ridden"] = nil
L["options_icons_dune_rider"] = nil
L["options_icons_dune_rider_desc"] = nil

L["options_icons_scavenger_of_the_sands"] = nil
L["options_icons_scavenger_of_the_sands_desc"] = nil

L["elusive_alpaca"] = "餵羊駝濱海綜合綠色蔬菜以學習坐騎。 在一個位置出現10分鐘，然後很久才重生。"

-------------------------------------------------------------------------------
---------------------------------- WARFRONTS ----------------------------------
-------------------------------------------------------------------------------

L["boulderfist_outpost"] = nil
L["burning_goliath_note"] = nil
L["cresting_goliath_note"] = nil
L["rumbling_goliath_note"] = nil
L["thundering_goliath_note"] = nil
L["echo_of_myzrael_note"] = nil
L["frightened_kodo_note"] = nil

-------------------------------------------------------------------------------
----------------------------------- ZULDAZAR ----------------------------------
-------------------------------------------------------------------------------

L["murderbeak_note"] = nil
L["vukuba_note"] = nil

L["cache_of_secrets_note"] = nil
L["da_white_shark_note"] = nil
L["dazars_forgotten_chest_note"] = nil
L["gift_of_the_brokenhearted_note"] = nil
L["offerings_of_the_chosen_note"] = nil
L["riches_of_tornowa_note"] = nil
L["spoils_of_pandaria_note"] = nil
L["tiny_voodoo_mask_note"] = nil
L["warlords_cache_note"] = nil

L["karaga_note"] = nil
L["talia_spark_note"] = nil
L["zujai_note"] = nil

L["kuafon_note"] = nil
L["torcali_note"] = nil

L["totem_of_paku_note"] = nil
L["options_icons_paku_totems"] = nil
L["options_icons_paku_totems_desc"] = nil

L["tales_gonk_note"] = nil
L["tales_gral_note"] = nil
L["tales_jani_note"] = nil
L["tales_paku_note"] = nil
L["tales_rezan_note"] = nil
L["tales_shadra_note"] = nil
L["tales_torcali_note"] = nil
L["tales_zandalar_note"] = nil

L["azuresail_note"] = nil
L["thunderfoot_note"] = nil
L["options_icons_life_finds_a_way"] = nil
L["options_icons_life_finds_a_way_desc"] = nil

-------------------------------------------------------------------------------
--------------------------------- ACROSS ZONES --------------------------------
-------------------------------------------------------------------------------

L["goramor_note"] = nil
L["makafon_note"] = nil
L["stompy_note"] = nil
L["options_icons_brutosaurs"] = nil
L["options_icons_brutosaurs_desc"] = nil

L["charged_junk_note"] = nil
L["feathered_junk_note"] = nil
L["golden_junk_note"] = nil
L["great_hat_junk_note"] = nil
L["hunter_junk_note"] = nil
L["loa_road_junk_note"] = nil
L["nazwathan_junk_note"] = nil
L["redrock_junk_note"] = nil
L["ringhorn_junk_note"] = nil
L["saurid_junk_note"] = nil
L["snapjaw_junk_note"] = nil
L["vilescale_junk_note"] = nil
L["options_icons_get_hekd"] = nil
L["options_icons_get_hekd_desc"] = nil

L["options_icons_mushroom_harvest"] = nil
L["options_icons_mushroom_harvest_desc"] = nil

L["options_icons_tales_of_de_loa"] = nil
L["options_icons_tales_of_de_loa_desc"] = nil

L["jani_note"] = nil
L["rezan_note"] = nil
L["bow_to_your_masters_note"] = nil
L["options_icons_bow_to_your_masters"] = nil
L["options_icons_bow_to_your_masters_desc"] = nil

L["alisha_note"] = nil
L["elijah_note"] = nil
L["raal_note"] = nil
L["sausage_sampler_note"] = nil
L["options_icons_sausage_sampler"] = nil
L["options_icons_sausage_sampler_desc"] = nil

L["three_sheets_note"] = nil
L["options_icons_three_sheets"] = nil
L["options_icons_three_sheets_desc"] = nil

L["options_icons_daily_chests_desc"] = "顯示寶箱位置 (每日可拾取的)。"
L["options_icons_daily_chests"] = "寶箱"

L["supply_chest"] = "戰爭補給箱"
L["supply_chest_note"] = nil
L["supply_single_drop"] = nil
L["options_icons_supplies_desc"] = "顯示戰爭補給箱的所有可能位置。"
L["options_icons_supplies"] = "戰爭補給空投"

L["secret_supply_chest"] = nil
L["secret_supply_chest_note"] = nil
L["options_icons_secret_supplies"] = nil
L["options_icons_secret_supplies_desc"] = nil

------------------------------------------------------------------------------
-------------------------------- TIMELESS ISLE --------------------------------
-------------------------------------------------------------------------------

L["cavern_of_lost_spirits"] = "在孤魂岩洞内。"
L["looted_twice"] = "此角色从未击杀此稀有。今天它可以拾取两次。"
L["neverending_spritewood"] = "无宁魂木"
L["neverending_spritewood_note"] = "打破无宁魂木之后，获得 {spell:144052} 负面效果，尽你所能击杀许多 {npc:71824}！"
L["zarhym_note"] = "每天可以和 {npc:71876} 交谈进入 {spell:144145} 并尝试找回他的身体。"

L["archiereus_note"] = "从 {npc:73306} 购买一个 {item:103684} 来召唤此稀有。"
L["chelon_note"] = "点击显眼的空壳来刷新稀有。"
L["cranegnasher_note"] = "从南侧风筝一个 {npc:72095} 到顶上鹤的尸体。"
L["dread_ship_note"] = "从 {npc:73279} 拾取 {item:104115} 并在被诅咒的墓碑使用来召唤稀有。"
L["emerald_gander_note"] = "击杀天神庭院周围的 {npc:72762} 直到 {npc:73158} 刷新。"
L["evermaw_note"] = "绕着整个岛屿顺时针游泳。"
L["great_turtle_furyshell_note"] = "击杀 {npc:72764} 或 {npc:72763} 直到 {npc:73161} 刷新。"
L["imperial_python_note"] = "击杀天神庭院周围的 {npc:72841} 直到 {npc:73163} 刷新。"
L["ironfur_steelhorn_note"] = "击杀天神庭院周围的 {npc:72844} 直到 {npc:73160} 刷新。"
L["karkanos_note"] = "和 {npc:72151} 交谈来钓出稀有。实在太难了！"
L["monstrous_spineclaw_note"] = "击杀岛屿周围的 {npc:72766} 直到 {npc:73166} 刷新。"
L["rattleskew_note"] = "击杀数波 {npc:72033} 直到稀有出现。"
L["spelurk_cave"] = "{npc:71864} 洞穴内。"
L["spelurk_note"] = [[
打破进入 {npc:71864} 洞穴，找到一个找到散布在岛上的丢失的文物之一，并使用技能在在阻挡入口的岩石上。

• {spell:147278}
• {spell:149333}
• {spell:149345}
• {spell:149350}

如果找不到文物，可以使用 {item:70161}（或坐垫类玩具）在岩石前面。坐下，然后站起来直走进入。
]]
L["zhugon_note"] = "当酿酒事件激活，击杀 {npc:71908} 并打破酒桶直到稀有出现。"

L["blazing_chest"] = "炽燃宝箱"
L["moss_covered_chest"] = "覆苔宝箱"
L["skull_covered_chest"] = "嵌颅宝箱"
L["smoldering_chest"] = "阴燃宝箱"
L["sturdy_chest"] = "坚固宝箱"
L["sturdy_chest_note"] = "攻击 {npc:73531} 被带到这里。"

L["gleaming_treasure_satchel_note"] = "沿着船上的绳索行走，然后跳到挎包悬挂的那根杆子上。"
L["gleaming_treasure_chest_note"] = "跳上柱子到达宝藏。"
L["mist_covered_treasure_chest_note"] = [[
需要先拾取闪闪发光的宝箱和绳索捆扎的宝箱。

点击发光的仙鹤雕像飞上到宝藏。
]]
L["ropebound_treasure_chest_note"] = "走绳子到达宝藏。"
L["sunken_treasure_note"] = "杀死沉船上的精英以获取钥匙。"

-------------------------------------------------------------------------------
--------------------------------- ACROSS ZONES --------------------------------
-------------------------------------------------------------------------------

L["zandalari_warbringer_note"] = [[
每日可以多次拾取。

{npc:69842} 坐骑的颜色决定了掉落坐骑的颜色。
]]
L["zandalari_warbringer_killed"] = "{npc:69842} 已击杀。"