-- 事件名称
---@alias EventString
--- | "PLAYER_REGEN_DISABLED" -- 进入战斗
--- | "PLAYER_ENTERING_WORLD" reload/切换地图/加载地图
--- | "BAG_UPDATE" -- 背包物品改变(物品、装备)
--- | "BAG_UPDATE_COOLDOWN"
--- | "PLAYER_EQUIPMENT_CHANGED" 装备改变（物品、装备）
--- | "PLAYER_TARGET_CHANGED" -- 目标改变（脚本、触发器）
--- | "PLAYER_TALENT_UPDATE"  -- 天赋改变（技能）
--- | "SPELLS_CHANGED" -- 技能改变（技能）
--- | "UNIT_SPELLCAST_SUCCEEDED" -- 单位施法成功
--- | "UNIT_AURA"  -- 单位光环改变
--- | "MODIFIER_STATE_CHANGED"  -- 修饰按键按下CTRL、SHIFT、ALT
--- | "UPDATE_MOUSEOVER_UNIT"  -- 鼠标执行目标改变
--- | "ZONE_CHANGED" -- 区域改变
--- | "MOUNT_JOURNAL_USABILITY_CHANGED" -- 坐骑可用改变
--- | "NEW_MOUNT_ADDED" -- 学会新的坐骑
--- | "NEW_PET_ADDED"
--- | "PET_BAR_UPDATE_COOLDOWN"
--- | "NEW_TOY_ADDED"
--- | "HB_UNIT_AURA"  -- 自定义事件（光环改变）
--- | "HB_GCD_UPDATE"  -- 自定义事件（GCD更新）
--- | "HB_FRAME_CHANGE" -- 自定义事件（框体状态变化：监听框体是否显示）
