-- 宏条件：对象条件
---@alias MacroTargetCondType
--- | "player"
--- | "target"
--- | "targettarget"
--- | "focus"
--- | "mouseover"
--- | "none"


-- 宏条件：布尔条件
---@alias MacroBooleanCondType
--- | "exists"
--- | "help"
--- | "dead" 
--- | "party"
--- | "raid"
--- | "unithasvehicleui" 
--- | "advflyable"
--- | "canexitvehicle"
--- | "channeling" 
--- | "combat"
--- | "equipped"
--- | "worn" 
--- | "flyable"
--- | "flying"
--- | "form" 
--- | "stance"
--- | "group"
--- | "indoors" 
--- | "known"
--- | "mounted"
--- | "pet" 
--- | "petFamily"
--- | "petbattle"
--- | "resting"
--- | "spec"
--- | "stealth" 
--- | "swimming"
--- | "mod"
--- | "btn"
--- | "unknow"

-- 宏命令
---@alias MacroCmd
--- | "use"
